/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Role this associated entity has with the customer
 */
public enum AssociatedRole {
  
  AUTHORIZED_PERSON("AUTHORIZED_PERSON"),
  
  UNAUTHORIZED_PERSON("UNAUTHORIZED_PERSON"),
  
  DIRECTOR("DIRECTOR"),
  
  COMPANY_SECRETARY("COMPANY_SECRETARY"),
  
  SHAREHOLDER("SHAREHOLDER"),
  
  PARTNER("PARTNER"),
  
  TRUSTEE("TRUSTEE"),
  
  BENEFICIAL_OWNER("BENEFICIAL_OWNER"),
  
  RESIGNED_OFFICER("RESIGNED_OFFICER"),
  
  OTHER("OTHER");

  private String value;

  AssociatedRole(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static AssociatedRole fromValue(String text) {
    for (AssociatedRole b : AssociatedRole.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}

