/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.BankAccountCommentType;
import org.openapitools.client.model.BankAccountComponent;

/**
 * Comment emitted during bank account verification
 */
@ApiModel(description = "Comment emitted during bank account verification")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class BankAccountComment {
  @JsonProperty("type")
  private BankAccountCommentType type = null;

  @JsonProperty("message")
  private String message;

  @JsonProperty("component")
  private BankAccountComponent component = null;

  public BankAccountComment type(BankAccountCommentType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public BankAccountCommentType getType() {
    return type;
  }

  public void setType(BankAccountCommentType type) {
    this.type = type;
  }

  public BankAccountComment message(String message) {
    this.message = message;
    return this;
  }

   /**
   * A comment about the bank account
   * @return message
  **/
  @ApiModelProperty(required = true, value = "A comment about the bank account")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public BankAccountComment component(BankAccountComponent component) {
    this.component = component;
    return this;
  }

   /**
   * Get component
   * @return component
  **/
  @ApiModelProperty(value = "")
  public BankAccountComponent getComponent() {
    return component;
  }

  public void setComponent(BankAccountComponent component) {
    this.component = component;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccountComment bankAccountComment = (BankAccountComment) o;
    return Objects.equals(this.type, bankAccountComment.type) &&
        Objects.equals(this.message, bankAccountComment.message) &&
        Objects.equals(this.component, bankAccountComment.component);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, message, component);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccountComment {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

