/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The set of capabilities which can be granted in the permissions system
 */
public enum CapabilityType {
  
  ROOT("ROOT"),
  
  EDIT_PROFILE("EDIT_PROFILE"),
  
  READ_PROFILE("READ_PROFILE"),
  
  CREATE_PROFILE("CREATE_PROFILE"),
  
  DELETE_PROFILE("DELETE_PROFILE"),
  
  CREATE_ROLE("CREATE_ROLE"),
  
  EDIT_ROLE("EDIT_ROLE"),
  
  DELETE_ROLE("DELETE_ROLE"),
  
  EDIT_PROFILE_COLLECTED_DATA("EDIT_PROFILE_COLLECTED_DATA"),
  
  READ_PROFILE_COLLECTED_DATA("READ_PROFILE_COLLECTED_DATA"),
  
  READ_PROFILE_COLLECTION_STEPS("READ_PROFILE_COLLECTION_STEPS"),
  
  EDIT_PROFILE_COLLECTION_STEPS("EDIT_PROFILE_COLLECTION_STEPS"),
  
  EDIT_DOCUMENT_IMAGE("EDIT_DOCUMENT_IMAGE"),
  
  READ_DOCUMENT_IMAGE("READ_DOCUMENT_IMAGE"),
  
  UPLOAD_DOCUMENT_IMAGE("UPLOAD_DOCUMENT_IMAGE"),
  
  PURCHASE_FILING_DOCUMENT("PURCHASE_FILING_DOCUMENT"),
  
  CREATE_TASK_NOTE("CREATE_TASK_NOTE"),
  
  DELETE_TASK_NOTE("DELETE_TASK_NOTE"),
  
  CUSTOM_AUTHOR_NOTE("CUSTOM_AUTHOR_NOTE"),
  
  ASSIGN_PRODUCT_APPLICATION("ASSIGN_PRODUCT_APPLICATION"),
  
  READ_PRODUCT_APPLICATION("READ_PRODUCT_APPLICATION"),
  
  CREATE_PRODUCT_APPLICATION("CREATE_PRODUCT_APPLICATION"),
  
  EDIT_PRODUCT_APPLICATION_STATUS("EDIT_PRODUCT_APPLICATION_STATUS"),
  
  CREATE_PROFILE_TASK("CREATE_PROFILE_TASK"),
  
  EDIT_CONVERSATION("EDIT_CONVERSATION"),
  
  RUN_CHECK("RUN_CHECK"),
  
  CREATE_PROFILE_TAG("CREATE_PROFILE_TAG"),
  
  DELETE_PROFILE_TAG("DELETE_PROFILE_TAG"),
  
  READ_TASK("READ_TASK"),
  
  EDIT_TASK_COMPLETION_STATUS("EDIT_TASK_COMPLETION_STATUS"),
  
  MANAGE_PEP_AND_SANCTIONS_MATCHES("MANAGE_PEP_AND_SANCTIONS_MATCHES"),
  
  SEARCH("SEARCH"),
  
  CREATE_USER("CREATE_USER"),
  
  VIEW_USERS("VIEW_USERS"),
  
  VIEW_USER("VIEW_USER"),
  
  EDIT_USER("EDIT_USER"),
  
  EDIT_USER_ROLE("EDIT_USER_ROLE"),
  
  EDIT_USER_PASSWORD("EDIT_USER_PASSWORD"),
  
  EDIT_USER_FILTER_SETS("EDIT_USER_FILTER_SETS"),
  
  VIEW_APPLICATION("VIEW_APPLICATION"),
  
  EDIT_PAYMENT("EDIT_PAYMENT"),
  
  VIEW_CONFIG("VIEW_CONFIG"),
  
  EDIT_CONFIG("EDIT_CONFIG"),
  
  VIEW_CONFIG_CREDENTIALS("VIEW_CONFIG_CREDENTIALS"),
  
  VIEW_REPORT("VIEW_REPORT"),
  
  CREATE_REPORT("CREATE_REPORT"),
  
  DELETE_REPORT("DELETE_REPORT"),
  
  EDIT_REPORT("EDIT_REPORT");

  private String value;

  CapabilityType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CapabilityType fromValue(String text) {
    for (CapabilityType b : CapabilityType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}

