/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.List;
import org.openapitools.client.model.CheckResourceBase;
import org.openapitools.client.model.CheckResourceBaseProviders;
import org.openapitools.client.model.CheckState;
import org.openapitools.client.model.CheckVariant;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.IndividualData;

/**
 * For details refer to [Check Reference](/reference/checks/individuals/peps-and-sanctions)
 */
@ApiModel(description = "For details refer to [Check Reference](/reference/checks/individuals/peps-and-sanctions)")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class CheckResourcePepsAndSanctionsScreen extends CheckResourceBase {
  /**
   * The type of check being ran
   */
  public enum CheckTypeEnum {
    PEPS_AND_SANCTIONS_SCREEN("PEPS_AND_SANCTIONS_SCREEN");

    private String value;

    CheckTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CheckTypeEnum fromValue(String text) {
      for (CheckTypeEnum b : CheckTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
  }

  @JsonProperty("check_type")
  private CheckTypeEnum checkType;

  @JsonProperty("disable_initial_screen")
  private Boolean disableInitialScreen;

  @JsonProperty("disable_monitoring")
  private Boolean disableMonitoring;

  @JsonProperty("input_data")
  private IndividualData inputData = null;

  @JsonProperty("output_data")
  private Object outputData = null;

  /**
   * The meaning of the result will depend on your provider and settings.
   */
  public enum ResultEnum {
    PASS("Pass"),
    
    REFER("Refer"),
    
    PEP("PEP"),
    
    SANCTION("Sanction"),
    
    MEDIA("Media"),
    
    ERROR("Error");

    private String value;

    ResultEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResultEnum fromValue(String text) {
      for (ResultEnum b : ResultEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
  }

  @JsonProperty("result")
  private ResultEnum result;

  public CheckResourcePepsAndSanctionsScreen checkType(CheckTypeEnum checkType) {
    this.checkType = checkType;
    return this;
  }

   /**
   * The type of check being ran
   * @return checkType
  **/
  @ApiModelProperty(value = "The type of check being ran")
  public CheckTypeEnum getCheckType() {
    return checkType;
  }

  public void setCheckType(CheckTypeEnum checkType) {
    this.checkType = checkType;
  }

  public CheckResourcePepsAndSanctionsScreen disableInitialScreen(Boolean disableInitialScreen) {
    this.disableInitialScreen = disableInitialScreen;
    return this;
  }

   /**
   * Defaults to &#x60;false&#x60;.  If &#x60;true&#x60; do not perform an initial screen and only monitor
   * @return disableInitialScreen
  **/
  @ApiModelProperty(value = "Defaults to `false`.  If `true` do not perform an initial screen and only monitor")
  public Boolean getDisableInitialScreen() {
    return disableInitialScreen;
  }

  public void setDisableInitialScreen(Boolean disableInitialScreen) {
    this.disableInitialScreen = disableInitialScreen;
  }

  public CheckResourcePepsAndSanctionsScreen disableMonitoring(Boolean disableMonitoring) {
    this.disableMonitoring = disableMonitoring;
    return this;
  }

   /**
   * Defaults to &#x60;false&#x60;. If &#x60;true&#x60; ongoing monitoring will be disabled
   * @return disableMonitoring
  **/
  @ApiModelProperty(value = "Defaults to `false`. If `true` ongoing monitoring will be disabled")
  public Boolean getDisableMonitoring() {
    return disableMonitoring;
  }

  public void setDisableMonitoring(Boolean disableMonitoring) {
    this.disableMonitoring = disableMonitoring;
  }

  public CheckResourcePepsAndSanctionsScreen inputData(IndividualData inputData) {
    this.inputData = inputData;
    return this;
  }

   /**
   * Get inputData
   * @return inputData
  **/
  @ApiModelProperty(value = "")
  public IndividualData getInputData() {
    return inputData;
  }

  public void setInputData(IndividualData inputData) {
    this.inputData = inputData;
  }

  public CheckResourcePepsAndSanctionsScreen outputData(Object outputData) {
    this.outputData = outputData;
    return this;
  }

   /**
   * The resultant output of the check.  **Note**: This was correct at the time the check was performed. Some check types will go out of date over time
   * @return outputData
  **/
  @ApiModelProperty(value = "The resultant output of the check.  **Note**: This was correct at the time the check was performed. Some check types will go out of date over time")
  public Object getOutputData() {
    return outputData;
  }

  public void setOutputData(Object outputData) {
    this.outputData = outputData;
  }

  public CheckResourcePepsAndSanctionsScreen result(ResultEnum result) {
    this.result = result;
    return this;
  }

   /**
   * The meaning of the result will depend on your provider and settings.
   * @return result
  **/
  @ApiModelProperty(value = "The meaning of the result will depend on your provider and settings.")
  public ResultEnum getResult() {
    return result;
  }

  public void setResult(ResultEnum result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckResourcePepsAndSanctionsScreen checkResourcePepsAndSanctionsScreen = (CheckResourcePepsAndSanctionsScreen) o;
    return Objects.equals(this.checkType, checkResourcePepsAndSanctionsScreen.checkType) &&
        Objects.equals(this.disableInitialScreen, checkResourcePepsAndSanctionsScreen.disableInitialScreen) &&
        Objects.equals(this.disableMonitoring, checkResourcePepsAndSanctionsScreen.disableMonitoring) &&
        Objects.equals(this.inputData, checkResourcePepsAndSanctionsScreen.inputData) &&
        Objects.equals(this.outputData, checkResourcePepsAndSanctionsScreen.outputData) &&
        Objects.equals(this.result, checkResourcePepsAndSanctionsScreen.result) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkType, disableInitialScreen, disableMonitoring, inputData, outputData, result, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckResourcePepsAndSanctionsScreen {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    checkType: ").append(toIndentedString(checkType)).append("\n");
    sb.append("    disableInitialScreen: ").append(toIndentedString(disableInitialScreen)).append("\n");
    sb.append("    disableMonitoring: ").append(toIndentedString(disableMonitoring)).append("\n");
    sb.append("    inputData: ").append(toIndentedString(inputData)).append("\n");
    sb.append("    outputData: ").append(toIndentedString(outputData)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

