/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.List;
import org.openapitools.client.model.CheckResourceBase;
import org.openapitools.client.model.CheckResourceBaseProviders;
import org.openapitools.client.model.CheckState;
import org.openapitools.client.model.CheckVariant;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.IndividualData;

/**
 * For details refer to [Check Reference](/reference/checks/individuals/document-fetch)
 */
@ApiModel(description = "For details refer to [Check Reference](/reference/checks/individuals/document-fetch)")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class CheckResourceDocumentFetch extends CheckResourceBase {
  /**
   * The type of check being ran
   */
  public enum CheckTypeEnum {
    DOCUMENT_FETCH("DOCUMENT_FETCH");

    private String value;

    CheckTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CheckTypeEnum fromValue(String text) {
      for (CheckTypeEnum b : CheckTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
  }

  @JsonProperty("check_type")
  private CheckTypeEnum checkType;

  /**
   * The source the document result is being fetched from
   */
  public enum SourceEnum {
    JUMIO("JUMIO"),
    
    ONFIDO("ONFIDO");

    private String value;

    SourceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceEnum fromValue(String text) {
      for (SourceEnum b : SourceEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
  }

  @JsonProperty("source")
  private SourceEnum source;

  @JsonProperty("reference")
  private String reference;

  @JsonProperty("input_data")
  private IndividualData inputData = null;

  @JsonProperty("output_data")
  private Object outputData = null;

  /**
   * The meaning of the result will depend on your provider and settings
   */
  public enum ResultEnum {
    PASS("Pass"),
    
    FAIL("Fail"),
    
    ERROR("Error");

    private String value;

    ResultEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResultEnum fromValue(String text) {
      for (ResultEnum b : ResultEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
  }

  @JsonProperty("result")
  private ResultEnum result;

  public CheckResourceDocumentFetch checkType(CheckTypeEnum checkType) {
    this.checkType = checkType;
    return this;
  }

   /**
   * The type of check being ran
   * @return checkType
  **/
  @ApiModelProperty(value = "The type of check being ran")
  public CheckTypeEnum getCheckType() {
    return checkType;
  }

  public void setCheckType(CheckTypeEnum checkType) {
    this.checkType = checkType;
  }

  public CheckResourceDocumentFetch source(SourceEnum source) {
    this.source = source;
    return this;
  }

   /**
   * The source the document result is being fetched from
   * @return source
  **/
  @ApiModelProperty(required = true, value = "The source the document result is being fetched from")
  public SourceEnum getSource() {
    return source;
  }

  public void setSource(SourceEnum source) {
    this.source = source;
  }

  public CheckResourceDocumentFetch reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * The source&#39;s document reference, refer to specific provider documentation
   * @return reference
  **/
  @ApiModelProperty(required = true, value = "The source's document reference, refer to specific provider documentation")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public CheckResourceDocumentFetch inputData(IndividualData inputData) {
    this.inputData = inputData;
    return this;
  }

   /**
   * Get inputData
   * @return inputData
  **/
  @ApiModelProperty(value = "")
  public IndividualData getInputData() {
    return inputData;
  }

  public void setInputData(IndividualData inputData) {
    this.inputData = inputData;
  }

  public CheckResourceDocumentFetch outputData(Object outputData) {
    this.outputData = outputData;
    return this;
  }

   /**
   * The resultant output of the check.  **Note**: This was correct at the time the check was performed. Some check types will go out of date over time
   * @return outputData
  **/
  @ApiModelProperty(value = "The resultant output of the check.  **Note**: This was correct at the time the check was performed. Some check types will go out of date over time")
  public Object getOutputData() {
    return outputData;
  }

  public void setOutputData(Object outputData) {
    this.outputData = outputData;
  }

  public CheckResourceDocumentFetch result(ResultEnum result) {
    this.result = result;
    return this;
  }

   /**
   * The meaning of the result will depend on your provider and settings
   * @return result
  **/
  @ApiModelProperty(value = "The meaning of the result will depend on your provider and settings")
  public ResultEnum getResult() {
    return result;
  }

  public void setResult(ResultEnum result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckResourceDocumentFetch checkResourceDocumentFetch = (CheckResourceDocumentFetch) o;
    return Objects.equals(this.checkType, checkResourceDocumentFetch.checkType) &&
        Objects.equals(this.source, checkResourceDocumentFetch.source) &&
        Objects.equals(this.reference, checkResourceDocumentFetch.reference) &&
        Objects.equals(this.inputData, checkResourceDocumentFetch.inputData) &&
        Objects.equals(this.outputData, checkResourceDocumentFetch.outputData) &&
        Objects.equals(this.result, checkResourceDocumentFetch.result) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkType, source, reference, inputData, outputData, result, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckResourceDocumentFetch {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    checkType: ").append(toIndentedString(checkType)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    inputData: ").append(toIndentedString(inputData)).append("\n");
    sb.append("    outputData: ").append(toIndentedString(outputData)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

