/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.List;
import org.openapitools.client.model.CheckResourceBase;
import org.openapitools.client.model.CheckResourceBaseProviders;
import org.openapitools.client.model.CheckState;
import org.openapitools.client.model.CheckVariant;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.IndividualData;

/**
 * Please speak to your account manager for more information.
 */
@ApiModel(description = "Please speak to your account manager for more information.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class CheckResourceIndividualManualForm extends CheckResourceBase {
  /**
   * The type of check being ran
   */
  public enum CheckTypeEnum {
    INDIVIDUAL_MANUAL_FORM("INDIVIDUAL_MANUAL_FORM");

    private String value;

    CheckTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CheckTypeEnum fromValue(String text) {
      for (CheckTypeEnum b : CheckTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
  }

  @JsonProperty("check_type")
  private CheckTypeEnum checkType;

  @JsonProperty("form_id")
  private String formId;

  @JsonProperty("input_data")
  private IndividualData inputData = null;

  @JsonProperty("output_data")
  private IndividualData outputData = null;

  /**
   * The meaning of the result will depend on your provider and settings
   */
  public enum ResultEnum {
    PASS("Pass"),
    
    FAIL("Fail");

    private String value;

    ResultEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResultEnum fromValue(String text) {
      for (ResultEnum b : ResultEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
  }

  @JsonProperty("result")
  private ResultEnum result;

  public CheckResourceIndividualManualForm checkType(CheckTypeEnum checkType) {
    this.checkType = checkType;
    return this;
  }

   /**
   * The type of check being ran
   * @return checkType
  **/
  @ApiModelProperty(value = "The type of check being ran")
  public CheckTypeEnum getCheckType() {
    return checkType;
  }

  public void setCheckType(CheckTypeEnum checkType) {
    this.checkType = checkType;
  }

  public CheckResourceIndividualManualForm formId(String formId) {
    this.formId = formId;
    return this;
  }

   /**
   * The ID of the form being filled
   * @return formId
  **/
  @ApiModelProperty(value = "The ID of the form being filled")
  public String getFormId() {
    return formId;
  }

  public void setFormId(String formId) {
    this.formId = formId;
  }

  public CheckResourceIndividualManualForm inputData(IndividualData inputData) {
    this.inputData = inputData;
    return this;
  }

   /**
   * Get inputData
   * @return inputData
  **/
  @ApiModelProperty(value = "")
  public IndividualData getInputData() {
    return inputData;
  }

  public void setInputData(IndividualData inputData) {
    this.inputData = inputData;
  }

  public CheckResourceIndividualManualForm outputData(IndividualData outputData) {
    this.outputData = outputData;
    return this;
  }

   /**
   * Get outputData
   * @return outputData
  **/
  @ApiModelProperty(value = "")
  public IndividualData getOutputData() {
    return outputData;
  }

  public void setOutputData(IndividualData outputData) {
    this.outputData = outputData;
  }

  public CheckResourceIndividualManualForm result(ResultEnum result) {
    this.result = result;
    return this;
  }

   /**
   * The meaning of the result will depend on your provider and settings
   * @return result
  **/
  @ApiModelProperty(value = "The meaning of the result will depend on your provider and settings")
  public ResultEnum getResult() {
    return result;
  }

  public void setResult(ResultEnum result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckResourceIndividualManualForm checkResourceIndividualManualForm = (CheckResourceIndividualManualForm) o;
    return Objects.equals(this.checkType, checkResourceIndividualManualForm.checkType) &&
        Objects.equals(this.formId, checkResourceIndividualManualForm.formId) &&
        Objects.equals(this.inputData, checkResourceIndividualManualForm.inputData) &&
        Objects.equals(this.outputData, checkResourceIndividualManualForm.outputData) &&
        Objects.equals(this.result, checkResourceIndividualManualForm.result) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkType, formId, inputData, outputData, result, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckResourceIndividualManualForm {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    checkType: ").append(toIndentedString(checkType)).append("\n");
    sb.append("    formId: ").append(toIndentedString(formId)).append("\n");
    sb.append("    inputData: ").append(toIndentedString(inputData)).append("\n");
    sb.append("    outputData: ").append(toIndentedString(outputData)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

