/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.annotations.ApiModel;
import java.util.List;
import org.openapitools.client.model.CheckResourceBaseProviders;
import org.openapitools.client.model.CheckResourceCRABankAccountVerification;
import org.openapitools.client.model.CheckResourceCompanyCharitiesRegistry;
import org.openapitools.client.model.CheckResourceCompanyDocumentVerification;
import org.openapitools.client.model.CheckResourceCompanyFilingPurchase;
import org.openapitools.client.model.CheckResourceCompanyFilings;
import org.openapitools.client.model.CheckResourceCompanyManualForm;
import org.openapitools.client.model.CheckResourceCompanyOwnership;
import org.openapitools.client.model.CheckResourceCompanyPepsAndSanctionsScreen;
import org.openapitools.client.model.CheckResourceCompanyRegistry;
import org.openapitools.client.model.CheckResourceDocumentFetch;
import org.openapitools.client.model.CheckResourceDocumentVerification;
import org.openapitools.client.model.CheckResourceIdentityCheck;
import org.openapitools.client.model.CheckResourceIndividualManualForm;
import org.openapitools.client.model.CheckResourcePepsAndSanctionsScreen;
import org.openapitools.client.model.CheckState;
import org.openapitools.client.model.CheckVariant;
import org.openapitools.client.model.CompanyData;
import org.openapitools.client.model.Error;

/**
 * A single check run against a profile
 */
@ApiModel(description = "A single check run against a profile")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "check_type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = CheckResourceIdentityCheck.class, name = "IDENTITY_CHECK"),
  @JsonSubTypes.Type(value = CheckResourceDocumentVerification.class, name = "DOCUMENT_VERIFICATION"),
  @JsonSubTypes.Type(value = CheckResourceDocumentFetch.class, name = "DOCUMENT_FETCH"),
  @JsonSubTypes.Type(value = CheckResourcePepsAndSanctionsScreen.class, name = "PEPS_AND_SANCTIONS_SCREEN"),
  @JsonSubTypes.Type(value = CheckResourceCRABankAccountVerification.class, name = "CRA_BANK_ACCOUNT_VERIFICATION"),
  @JsonSubTypes.Type(value = CheckResourceCompanyRegistry.class, name = "COMPANY_REGISTRY"),
  @JsonSubTypes.Type(value = CheckResourceCompanyCharitiesRegistry.class, name = "COMPANY_CHARITIES_REGISTRY"),
  @JsonSubTypes.Type(value = CheckResourceCompanyOwnership.class, name = "COMPANY_OWNERSHIP"),
  @JsonSubTypes.Type(value = CheckResourceCompanyFilings.class, name = "COMPANY_FILINGS"),
  @JsonSubTypes.Type(value = CheckResourceCompanyFilingPurchase.class, name = "COMPANY_FILING_PURCHASE"),
  @JsonSubTypes.Type(value = CheckResourceCompanyPepsAndSanctionsScreen.class, name = "COMPANY_PEPS_AND_SANCTIONS_SCREEN"),
  @JsonSubTypes.Type(value = CheckResourceIndividualManualForm.class, name = "INDIVIDUAL_MANUAL_FORM"),
  @JsonSubTypes.Type(value = CheckResourceCompanyManualForm.class, name = "COMPANY_MANUAL_FORM"),
  @JsonSubTypes.Type(value = CheckResourceCompanyDocumentVerification.class, name = "COMPANY_DOCUMENT_VERIFICATION"),
})

public class CheckResource {

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash();
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckResource {\n");
    
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

