/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The type of a check run against a profile
 */
public enum CheckType {
  
  IDENTITY_CHECK("IDENTITY_CHECK"),
  
  DOCUMENT_VERIFICATION("DOCUMENT_VERIFICATION"),
  
  DOCUMENT_FETCH("DOCUMENT_FETCH"),
  
  PEPS_AND_SANCTIONS_SCREEN("PEPS_AND_SANCTIONS_SCREEN"),
  
  CRA_BANK_ACCOUNT_VERIFICATION("CRA_BANK_ACCOUNT_VERIFICATION"),
  
  COMPANY_REGISTRY("COMPANY_REGISTRY"),
  
  COMPANY_CHARITIES_REGISTRY("COMPANY_CHARITIES_REGISTRY"),
  
  COMPANY_OWNERSHIP("COMPANY_OWNERSHIP"),
  
  COMPANY_FILINGS("COMPANY_FILINGS"),
  
  COMPANY_FILING_PURCHASE("COMPANY_FILING_PURCHASE"),
  
  COMPANY_PEPS_AND_SANCTIONS_SCREEN("COMPANY_PEPS_AND_SANCTIONS_SCREEN"),
  
  INDIVIDUAL_MANUAL_FORM("INDIVIDUAL_MANUAL_FORM"),
  
  COMPANY_MANUAL_FORM("COMPANY_MANUAL_FORM"),
  
  COMPANY_DOCUMENT_VERIFICATION("COMPANY_DOCUMENT_VERIFICATION");

  private String value;

  CheckType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CheckType fromValue(String text) {
    for (CheckType b : CheckType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}

