/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.annotations.ApiModel;
import java.util.List;
import org.openapitools.client.model.CollectionStepAddressHistory;
import org.openapitools.client.model.CollectionStepDOB;
import org.openapitools.client.model.CollectionStepDocument;
import org.openapitools.client.model.CollectionStepEmail;
import org.openapitools.client.model.CollectionStepFullName;
import org.openapitools.client.model.CollectionStepNationality;
import org.openapitools.client.model.CollectionStepPhoneNumber;
import org.openapitools.client.model.DocumentCategory;
import org.openapitools.client.model.DocumentType;

/**
 * Collection steps are the data you wish to collect from a profile. In PassFort Collect the fields required to complete the step will be presented to the user. Collection steps are automatically removed from a profile when the data they collect is fulfilled. If a profile has &#x60;collection_steps&#x60;, all checks instructed on a profile will go into a &#x60;PENDING&#x60; state until all steps are completed. 
 */
@ApiModel(description = "Collection steps are the data you wish to collect from a profile. In PassFort Collect the fields required to complete the step will be presented to the user. Collection steps are automatically removed from a profile when the data they collect is fulfilled. If a profile has `collection_steps`, all checks instructed on a profile will go into a `PENDING` state until all steps are completed. ")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "collection_type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = CollectionStepAddressHistory.class, name = "ADDRESS_HISTORY"),
  @JsonSubTypes.Type(value = CollectionStepDOB.class, name = "DOB"),
  @JsonSubTypes.Type(value = CollectionStepFullName.class, name = "FULL_NAME"),
  @JsonSubTypes.Type(value = CollectionStepNationality.class, name = "NATIONALITY"),
  @JsonSubTypes.Type(value = CollectionStepDocument.class, name = "DOCUMENT"),
  @JsonSubTypes.Type(value = CollectionStepEmail.class, name = "EMAIL"),
  @JsonSubTypes.Type(value = CollectionStepPhoneNumber.class, name = "PHONE_NUMBER"),
})

public class CollectionStep {

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash();
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CollectionStep {\n");
    
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

