/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies the data to be collected
 */
public enum CollectionStepType {
  
  FULL_NAME("FULL_NAME"),
  
  DOB("DOB"),
  
  ADDRESS_HISTORY("ADDRESS_HISTORY"),
  
  NATIONALITY("NATIONALITY"),
  
  DOCUMENT("DOCUMENT"),
  
  EMAIL("EMAIL"),
  
  PHONE_NUMBER("PHONE_NUMBER");

  private String value;

  CollectionStepType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CollectionStepType fromValue(String text) {
    for (CollectionStepType b : CollectionStepType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}

