/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AreaOfActivity;
import org.openapitools.client.model.CompanyAddress;
import org.openapitools.client.model.CompanyContactDetails;
import org.openapitools.client.model.CompanyMetadataStructuredCompanyType;
import org.openapitools.client.model.CountryCode;
import org.openapitools.client.model.PreviousName;
import org.openapitools.client.model.SicCode;
import org.openapitools.client.model.TaxId;

/**
 * Collected data for a company
 */
@ApiModel(description = "Collected data for a company")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class CompanyMetadata {
  @JsonProperty("number")
  private String number;

  @JsonProperty("bvd_id")
  private String bvdId;

  @JsonProperty("bvd9")
  private String bvd9;

  @JsonProperty("isin")
  private String isin;

  @JsonProperty("lei")
  private String lei;

  @JsonProperty("uk_charity_commission_number")
  private String ukCharityCommissionNumber;

  @JsonProperty("tax_ids")
  private List<TaxId> taxIds = null;

  @JsonProperty("name")
  private String name;

  @JsonProperty("previous_names")
  private List<PreviousName> previousNames = null;

  @JsonProperty("addresses")
  private List<CompanyAddress> addresses = null;

  @JsonProperty("country_of_incorporation")
  private CountryCode countryOfIncorporation = null;

  @JsonProperty("state_of_incorporation")
  private String stateOfIncorporation;

  @JsonProperty("jurisdiction")
  private String jurisdiction;

  @JsonProperty("areas_of_activity")
  private List<AreaOfActivity> areasOfActivity = null;

  @JsonProperty("description")
  private String description;

  @JsonProperty("number_of_employees")
  private BigDecimal numberOfEmployees;

  @JsonProperty("registry")
  private String registry;

  @JsonProperty("sic_codes")
  private List<SicCode> sicCodes = null;

  @JsonProperty("is_active")
  private Boolean isActive;

  @JsonProperty("contact_details")
  private CompanyContactDetails contactDetails = null;

  @JsonProperty("incorporation_date")
  private String incorporationDate;

  @JsonProperty("company_type")
  private String companyType;

  @JsonProperty("structured_company_type")
  private CompanyMetadataStructuredCompanyType structuredCompanyType = null;

  @JsonProperty("company_type_description")
  private String companyTypeDescription;

  public CompanyMetadata number(String number) {
    this.number = number;
    return this;
  }

   /**
   * The identifier given to the company by the company register on which it is registered.  For example PassFort&#39;s company number is [09565115](https://beta.companieshouse.gov.uk/company/09565115).  Data providers expect this number to be in a certain format, which depends on the jurisdiction and provider.  To ensure that you have the correct number for your provider the [company search](/developer/v4/api-reference/Search/search-companies) feature can be used.
   * @return number
  **/
  @ApiModelProperty(value = "The identifier given to the company by the company register on which it is registered.  For example PassFort's company number is [09565115](https://beta.companieshouse.gov.uk/company/09565115).  Data providers expect this number to be in a certain format, which depends on the jurisdiction and provider.  To ensure that you have the correct number for your provider the [company search](/developer/v4/api-reference/Search/search-companies) feature can be used.")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public CompanyMetadata bvdId(String bvdId) {
    this.bvdId = bvdId;
    return this;
  }

   /**
   * Bureau van Dijk identifier
   * @return bvdId
  **/
  @ApiModelProperty(value = "Bureau van Dijk identifier")
  public String getBvdId() {
    return bvdId;
  }

  public void setBvdId(String bvdId) {
    this.bvdId = bvdId;
  }

  public CompanyMetadata bvd9(String bvd9) {
    this.bvd9 = bvd9;
    return this;
  }

   /**
   * Bureau van Dijk 9 identifier
   * @return bvd9
  **/
  @ApiModelProperty(value = "Bureau van Dijk 9 identifier")
  public String getBvd9() {
    return bvd9;
  }

  public void setBvd9(String bvd9) {
    this.bvd9 = bvd9;
  }

  public CompanyMetadata isin(String isin) {
    this.isin = isin;
    return this;
  }

   /**
   * International Securities Identification Number
   * @return isin
  **/
  @ApiModelProperty(value = "International Securities Identification Number")
  public String getIsin() {
    return isin;
  }

  public void setIsin(String isin) {
    this.isin = isin;
  }

  public CompanyMetadata lei(String lei) {
    this.lei = lei;
    return this;
  }

   /**
   * Global Legal Entity Identifier
   * @return lei
  **/
  @ApiModelProperty(value = "Global Legal Entity Identifier")
  public String getLei() {
    return lei;
  }

  public void setLei(String lei) {
    this.lei = lei;
  }

  public CompanyMetadata ukCharityCommissionNumber(String ukCharityCommissionNumber) {
    this.ukCharityCommissionNumber = ukCharityCommissionNumber;
    return this;
  }

   /**
   * UK Charities Commission Number
   * @return ukCharityCommissionNumber
  **/
  @ApiModelProperty(value = "UK Charities Commission Number")
  public String getUkCharityCommissionNumber() {
    return ukCharityCommissionNumber;
  }

  public void setUkCharityCommissionNumber(String ukCharityCommissionNumber) {
    this.ukCharityCommissionNumber = ukCharityCommissionNumber;
  }

  public CompanyMetadata taxIds(List<TaxId> taxIds) {
    this.taxIds = taxIds;
    return this;
  }

  public CompanyMetadata addTaxIdsItem(TaxId taxIdsItem) {
    if (this.taxIds == null) {
      this.taxIds = new ArrayList<TaxId>();
    }
    this.taxIds.add(taxIdsItem);
    return this;
  }

   /**
   * Tax identifiers
   * @return taxIds
  **/
  @ApiModelProperty(value = "Tax identifiers")
  public List<TaxId> getTaxIds() {
    return taxIds;
  }

  public void setTaxIds(List<TaxId> taxIds) {
    this.taxIds = taxIds;
  }

  public CompanyMetadata name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The legal name of the company.  These are not guaranteed to be unique in some jurisdictions, and so PassFort uses the company jurisdction + number as the canonical company identifier.  Rather than fetching this from the company, it&#39;s often better parctise to get this from a basic or advanced registry check
   * @return name
  **/
  @ApiModelProperty(value = "The legal name of the company.  These are not guaranteed to be unique in some jurisdictions, and so PassFort uses the company jurisdction + number as the canonical company identifier.  Rather than fetching this from the company, it's often better parctise to get this from a basic or advanced registry check")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CompanyMetadata previousNames(List<PreviousName> previousNames) {
    this.previousNames = previousNames;
    return this;
  }

  public CompanyMetadata addPreviousNamesItem(PreviousName previousNamesItem) {
    if (this.previousNames == null) {
      this.previousNames = new ArrayList<PreviousName>();
    }
    this.previousNames.add(previousNamesItem);
    return this;
  }

   /**
   * Previous names of the company
   * @return previousNames
  **/
  @ApiModelProperty(value = "Previous names of the company")
  public List<PreviousName> getPreviousNames() {
    return previousNames;
  }

  public void setPreviousNames(List<PreviousName> previousNames) {
    this.previousNames = previousNames;
  }

  public CompanyMetadata addresses(List<CompanyAddress> addresses) {
    this.addresses = addresses;
    return this;
  }

  public CompanyMetadata addAddressesItem(CompanyAddress addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<CompanyAddress>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * List of addresses associated with the company
   * @return addresses
  **/
  @ApiModelProperty(value = "List of addresses associated with the company")
  public List<CompanyAddress> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<CompanyAddress> addresses) {
    this.addresses = addresses;
  }

  public CompanyMetadata countryOfIncorporation(CountryCode countryOfIncorporation) {
    this.countryOfIncorporation = countryOfIncorporation;
    return this;
  }

   /**
   * Get countryOfIncorporation
   * @return countryOfIncorporation
  **/
  @ApiModelProperty(value = "")
  public CountryCode getCountryOfIncorporation() {
    return countryOfIncorporation;
  }

  public void setCountryOfIncorporation(CountryCode countryOfIncorporation) {
    this.countryOfIncorporation = countryOfIncorporation;
  }

  public CompanyMetadata stateOfIncorporation(String stateOfIncorporation) {
    this.stateOfIncorporation = stateOfIncorporation;
    return this;
  }

   /**
   * This is required for companies in the USA and Canada
   * @return stateOfIncorporation
  **/
  @ApiModelProperty(value = "This is required for companies in the USA and Canada")
  public String getStateOfIncorporation() {
    return stateOfIncorporation;
  }

  public void setStateOfIncorporation(String stateOfIncorporation) {
    this.stateOfIncorporation = stateOfIncorporation;
  }

  public CompanyMetadata jurisdiction(String jurisdiction) {
    this.jurisdiction = jurisdiction;
    return this;
  }

   /**
   * The jurisdiction in which the company was incorporated, in the event that there are multiple possible jurisdictions
   * @return jurisdiction
  **/
  @ApiModelProperty(value = "The jurisdiction in which the company was incorporated, in the event that there are multiple possible jurisdictions")
  public String getJurisdiction() {
    return jurisdiction;
  }

  public void setJurisdiction(String jurisdiction) {
    this.jurisdiction = jurisdiction;
  }

  public CompanyMetadata areasOfActivity(List<AreaOfActivity> areasOfActivity) {
    this.areasOfActivity = areasOfActivity;
    return this;
  }

  public CompanyMetadata addAreasOfActivityItem(AreaOfActivity areasOfActivityItem) {
    if (this.areasOfActivity == null) {
      this.areasOfActivity = new ArrayList<AreaOfActivity>();
    }
    this.areasOfActivity.add(areasOfActivityItem);
    return this;
  }

   /**
   * The areas in which the business operates
   * @return areasOfActivity
  **/
  @ApiModelProperty(value = "The areas in which the business operates")
  public List<AreaOfActivity> getAreasOfActivity() {
    return areasOfActivity;
  }

  public void setAreasOfActivity(List<AreaOfActivity> areasOfActivity) {
    this.areasOfActivity = areasOfActivity;
  }

  public CompanyMetadata description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A free text description of the businesses activities
   * @return description
  **/
  @ApiModelProperty(value = "A free text description of the businesses activities")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CompanyMetadata numberOfEmployees(BigDecimal numberOfEmployees) {
    this.numberOfEmployees = numberOfEmployees;
    return this;
  }

   /**
   * The number of employees in the business
   * @return numberOfEmployees
  **/
  @ApiModelProperty(value = "The number of employees in the business")
  public BigDecimal getNumberOfEmployees() {
    return numberOfEmployees;
  }

  public void setNumberOfEmployees(BigDecimal numberOfEmployees) {
    this.numberOfEmployees = numberOfEmployees;
  }

  public CompanyMetadata registry(String registry) {
    this.registry = registry;
    return this;
  }

   /**
   * The name of the registry in which the company information was found
   * @return registry
  **/
  @ApiModelProperty(value = "The name of the registry in which the company information was found")
  public String getRegistry() {
    return registry;
  }

  public void setRegistry(String registry) {
    this.registry = registry;
  }

  public CompanyMetadata sicCodes(List<SicCode> sicCodes) {
    this.sicCodes = sicCodes;
    return this;
  }

  public CompanyMetadata addSicCodesItem(SicCode sicCodesItem) {
    if (this.sicCodes == null) {
      this.sicCodes = new ArrayList<SicCode>();
    }
    this.sicCodes.add(sicCodesItem);
    return this;
  }

   /**
   * A list of SIC codes describing the industries with which the company is concerned
   * @return sicCodes
  **/
  @ApiModelProperty(value = "A list of SIC codes describing the industries with which the company is concerned")
  public List<SicCode> getSicCodes() {
    return sicCodes;
  }

  public void setSicCodes(List<SicCode> sicCodes) {
    this.sicCodes = sicCodes;
  }

  public CompanyMetadata isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Whether the company is still active
   * @return isActive
  **/
  @ApiModelProperty(value = "Whether the company is still active")
  public Boolean getIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public CompanyMetadata contactDetails(CompanyContactDetails contactDetails) {
    this.contactDetails = contactDetails;
    return this;
  }

   /**
   * Get contactDetails
   * @return contactDetails
  **/
  @ApiModelProperty(value = "")
  public CompanyContactDetails getContactDetails() {
    return contactDetails;
  }

  public void setContactDetails(CompanyContactDetails contactDetails) {
    this.contactDetails = contactDetails;
  }

  public CompanyMetadata incorporationDate(String incorporationDate) {
    this.incorporationDate = incorporationDate;
    return this;
  }

   /**
   * Exact date in &#x60;YYYY-MM-DD&#x60; format
   * @return incorporationDate
  **/
  @ApiModelProperty(example = "1992-11-24", value = "Exact date in `YYYY-MM-DD` format")
  public String getIncorporationDate() {
    return incorporationDate;
  }

  public void setIncorporationDate(String incorporationDate) {
    this.incorporationDate = incorporationDate;
  }

  public CompanyMetadata companyType(String companyType) {
    this.companyType = companyType;
    return this;
  }

   /**
   * Company type identifier, as given by the provider, indicating the kind of liability its members are exposed to and whether it is publically traded
   * @return companyType
  **/
  @ApiModelProperty(value = "Company type identifier, as given by the provider, indicating the kind of liability its members are exposed to and whether it is publically traded")
  public String getCompanyType() {
    return companyType;
  }

  public void setCompanyType(String companyType) {
    this.companyType = companyType;
  }

  public CompanyMetadata structuredCompanyType(CompanyMetadataStructuredCompanyType structuredCompanyType) {
    this.structuredCompanyType = structuredCompanyType;
    return this;
  }

   /**
   * Get structuredCompanyType
   * @return structuredCompanyType
  **/
  @ApiModelProperty(value = "")
  public CompanyMetadataStructuredCompanyType getStructuredCompanyType() {
    return structuredCompanyType;
  }

  public void setStructuredCompanyType(CompanyMetadataStructuredCompanyType structuredCompanyType) {
    this.structuredCompanyType = structuredCompanyType;
  }

  public CompanyMetadata companyTypeDescription(String companyTypeDescription) {
    this.companyTypeDescription = companyTypeDescription;
    return this;
  }

   /**
   * Long name for the company type, indicating the kind of liability its members are exposed to, and whether it is publically traded
   * @return companyTypeDescription
  **/
  @ApiModelProperty(value = "Long name for the company type, indicating the kind of liability its members are exposed to, and whether it is publically traded")
  public String getCompanyTypeDescription() {
    return companyTypeDescription;
  }

  public void setCompanyTypeDescription(String companyTypeDescription) {
    this.companyTypeDescription = companyTypeDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyMetadata companyMetadata = (CompanyMetadata) o;
    return Objects.equals(this.number, companyMetadata.number) &&
        Objects.equals(this.bvdId, companyMetadata.bvdId) &&
        Objects.equals(this.bvd9, companyMetadata.bvd9) &&
        Objects.equals(this.isin, companyMetadata.isin) &&
        Objects.equals(this.lei, companyMetadata.lei) &&
        Objects.equals(this.ukCharityCommissionNumber, companyMetadata.ukCharityCommissionNumber) &&
        Objects.equals(this.taxIds, companyMetadata.taxIds) &&
        Objects.equals(this.name, companyMetadata.name) &&
        Objects.equals(this.previousNames, companyMetadata.previousNames) &&
        Objects.equals(this.addresses, companyMetadata.addresses) &&
        Objects.equals(this.countryOfIncorporation, companyMetadata.countryOfIncorporation) &&
        Objects.equals(this.stateOfIncorporation, companyMetadata.stateOfIncorporation) &&
        Objects.equals(this.jurisdiction, companyMetadata.jurisdiction) &&
        Objects.equals(this.areasOfActivity, companyMetadata.areasOfActivity) &&
        Objects.equals(this.description, companyMetadata.description) &&
        Objects.equals(this.numberOfEmployees, companyMetadata.numberOfEmployees) &&
        Objects.equals(this.registry, companyMetadata.registry) &&
        Objects.equals(this.sicCodes, companyMetadata.sicCodes) &&
        Objects.equals(this.isActive, companyMetadata.isActive) &&
        Objects.equals(this.contactDetails, companyMetadata.contactDetails) &&
        Objects.equals(this.incorporationDate, companyMetadata.incorporationDate) &&
        Objects.equals(this.companyType, companyMetadata.companyType) &&
        Objects.equals(this.structuredCompanyType, companyMetadata.structuredCompanyType) &&
        Objects.equals(this.companyTypeDescription, companyMetadata.companyTypeDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, bvdId, bvd9, isin, lei, ukCharityCommissionNumber, taxIds, name, previousNames, addresses, countryOfIncorporation, stateOfIncorporation, jurisdiction, areasOfActivity, description, numberOfEmployees, registry, sicCodes, isActive, contactDetails, incorporationDate, companyType, structuredCompanyType, companyTypeDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyMetadata {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    bvdId: ").append(toIndentedString(bvdId)).append("\n");
    sb.append("    bvd9: ").append(toIndentedString(bvd9)).append("\n");
    sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
    sb.append("    lei: ").append(toIndentedString(lei)).append("\n");
    sb.append("    ukCharityCommissionNumber: ").append(toIndentedString(ukCharityCommissionNumber)).append("\n");
    sb.append("    taxIds: ").append(toIndentedString(taxIds)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    previousNames: ").append(toIndentedString(previousNames)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    countryOfIncorporation: ").append(toIndentedString(countryOfIncorporation)).append("\n");
    sb.append("    stateOfIncorporation: ").append(toIndentedString(stateOfIncorporation)).append("\n");
    sb.append("    jurisdiction: ").append(toIndentedString(jurisdiction)).append("\n");
    sb.append("    areasOfActivity: ").append(toIndentedString(areasOfActivity)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    numberOfEmployees: ").append(toIndentedString(numberOfEmployees)).append("\n");
    sb.append("    registry: ").append(toIndentedString(registry)).append("\n");
    sb.append("    sicCodes: ").append(toIndentedString(sicCodes)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    contactDetails: ").append(toIndentedString(contactDetails)).append("\n");
    sb.append("    incorporationDate: ").append(toIndentedString(incorporationDate)).append("\n");
    sb.append("    companyType: ").append(toIndentedString(companyType)).append("\n");
    sb.append("    structuredCompanyType: ").append(toIndentedString(structuredCompanyType)).append("\n");
    sb.append("    companyTypeDescription: ").append(toIndentedString(companyTypeDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

