/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.FileResource;

/**
 * Definition used to create a new note (with optional associated files)
 */
@ApiModel(description = "Definition used to create a new note (with optional associated files)")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class CreateNoteResource {
  @JsonProperty("text")
  private String text;

  @JsonProperty("attachments")
  private List<FileResource> attachments = null;

  public CreateNoteResource text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Note text
   * @return text
  **/
  @ApiModelProperty(value = "Note text")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public CreateNoteResource attachments(List<FileResource> attachments) {
    this.attachments = attachments;
    return this;
  }

  public CreateNoteResource addAttachmentsItem(FileResource attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<FileResource>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
   * Associated files (if present)
   * @return attachments
  **/
  @ApiModelProperty(value = "Associated files (if present)")
  public List<FileResource> getAttachments() {
    return attachments;
  }

  public void setAttachments(List<FileResource> attachments) {
    this.attachments = attachments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateNoteResource createNoteResource = (CreateNoteResource) o;
    return Objects.equals(this.text, createNoteResource.text) &&
        Objects.equals(this.attachments, createNoteResource.attachments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, attachments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateNoteResource {\n");
    
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

