/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type of document being submitted
 */
public enum DocumentType {
  
  PASSPORT("PASSPORT"),
  
  DRIVING_LICENCE("DRIVING_LICENCE"),
  
  STATE_ID("STATE_ID"),
  
  VOTER_ID("VOTER_ID"),
  
  BIRTH_CERTIFICATE("BIRTH_CERTIFICATE"),
  
  BANK_STATEMENT("BANK_STATEMENT"),
  
  FACE_IMAGE("FACE_IMAGE"),
  
  UNKNOWN("UNKNOWN"),
  
  COMPANY_ACCOUNTS("COMPANY_ACCOUNTS"),
  
  COMPANY_CHANGE_OF_ADDRESS("COMPANY_CHANGE_OF_ADDRESS"),
  
  ANNUAL_RETURN("ANNUAL_RETURN"),
  
  CONFIRMATION_STATEMENT("CONFIRMATION_STATEMENT"),
  
  STATEMENT_OF_CAPITAL("STATEMENT_OF_CAPITAL"),
  
  CHANGE_OF_NAME("CHANGE_OF_NAME"),
  
  INCORPORATION("INCORPORATION"),
  
  LIQUIDATION("LIQUIDATION"),
  
  MISCELLANEOUS("MISCELLANEOUS"),
  
  MORTGAGE("MORTGAGE"),
  
  CHANGE_OF_OFFICERS("CHANGE_OF_OFFICERS"),
  
  RESOLUTION("RESOLUTION"),
  
  CREDIT_REPORT("CREDIT_REPORT"),
  
  CREDIT_CHECK("CREDIT_CHECK"),
  
  REGISTER_REPORT("REGISTER_REPORT"),
  
  REGISTER_CHECK("REGISTER_CHECK"),
  
  DATA_SUMMARY("DATA_SUMMARY"),
  
  CHANGE_OF_PSC("CHANGE_OF_PSC"),
  
  ADVERSE_MEDIA("ADVERSE_MEDIA"),
  
  TAX("TAX");

  private String value;

  DocumentType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DocumentType fromValue(String text) {
    for (DocumentType b : DocumentType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}

