/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.DecisionClass;

/**
 * Details of a document check
 */
@ApiModel(description = "Details of a document check")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class DocumentCheck {
  @JsonProperty("category")
  private String category;

  @JsonProperty("type")
  private String type;

  @JsonProperty("result")
  private DecisionClass result = null;

  public DocumentCheck category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Category of forgery check
   * @return category
  **/
  @ApiModelProperty(value = "Category of forgery check")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public DocumentCheck type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of forgery check
   * @return type
  **/
  @ApiModelProperty(value = "Type of forgery check")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public DocumentCheck result(DecisionClass result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public DecisionClass getResult() {
    return result;
  }

  public void setResult(DecisionClass result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentCheck documentCheck = (DocumentCheck) o;
    return Objects.equals(this.category, documentCheck.category) &&
        Objects.equals(this.type, documentCheck.type) &&
        Objects.equals(this.result, documentCheck.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, type, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentCheck {\n");
    
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

