/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Describes how this document should be used by the system
 */
public enum DocumentCategory {
  
  PROOF_OF_IDENTITY("PROOF_OF_IDENTITY"),
  
  PROOF_OF_SOURCE_OF_WEALTH("PROOF_OF_SOURCE_OF_WEALTH"),
  
  PROOF_OF_SOURCE_OF_FUNDS("PROOF_OF_SOURCE_OF_FUNDS"),
  
  PROOF_OF_ADDRESS("PROOF_OF_ADDRESS"),
  
  SUPPORTING("SUPPORTING"),
  
  COMPANY_FILING("COMPANY_FILING"),
  
  DATA_SUMMARY("DATA_SUMMARY"),
  
  PROOF_OF_BANK_ACCOUNT("PROOF_OF_BANK_ACCOUNT"),
  
  PROOF_OF_TAX_STATUS("PROOF_OF_TAX_STATUS");

  private String value;

  DocumentCategory(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DocumentCategory fromValue(String text) {
    for (DocumentCategory b : DocumentCategory.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}

