/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.CheckedDocumentField;
import org.openapitools.client.model.FieldCheckResult;

/**
 * DocumentResultFieldChecks
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class DocumentResultFieldChecks {
  @JsonProperty("field")
  private CheckedDocumentField field = null;

  @JsonProperty("result")
  private FieldCheckResult result = null;

  public DocumentResultFieldChecks field(CheckedDocumentField field) {
    this.field = field;
    return this;
  }

   /**
   * Get field
   * @return field
  **/
  @ApiModelProperty(value = "")
  public CheckedDocumentField getField() {
    return field;
  }

  public void setField(CheckedDocumentField field) {
    this.field = field;
  }

  public DocumentResultFieldChecks result(FieldCheckResult result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public FieldCheckResult getResult() {
    return result;
  }

  public void setResult(FieldCheckResult result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentResultFieldChecks documentResultFieldChecks = (DocumentResultFieldChecks) o;
    return Objects.equals(this.field, documentResultFieldChecks.field) &&
        Objects.equals(this.result, documentResultFieldChecks.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(field, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentResultFieldChecks {\n");
    
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

