/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.annotations.ApiModel;
import java.util.List;
import org.openapitools.client.model.AssociatedEntity;
import org.openapitools.client.model.CompanyCharityData;
import org.openapitools.client.model.CompanyData;
import org.openapitools.client.model.CompanyFiling;
import org.openapitools.client.model.CompanyMetadata;
import org.openapitools.client.model.Document;
import org.openapitools.client.model.IPLocation;
import org.openapitools.client.model.IndividualData;
import org.openapitools.client.model.Officers;
import org.openapitools.client.model.OwnershipStructure;
import org.openapitools.client.model.PersonalDetails;

/**
 * Base class for profile data. An entity is either an individual or a company
 */
@ApiModel(description = "Base class for profile data. An entity is either an individual or a company")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "entity_type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = IndividualData.class, name = "INDIVIDUAL"),
  @JsonSubTypes.Type(value = CompanyData.class, name = "COMPANY"),
})

public class EntityData {

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash();
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityData {\n");
    
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

