/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.EventData;
import org.openapitools.client.model.EventResolution;

/**
 * A single profile event (such as a PEP or Sanction match)
 */
@ApiModel(description = "A single profile event (such as a PEP or Sanction match)")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class EventResource {
  @JsonProperty("id")
  private String id;

  @JsonProperty("creation_date")
  private String creationDate = null;

  @JsonProperty("resolution")
  private EventResolution resolution = null;

  @JsonProperty("resolution_reason")
  private String resolutionReason;

  @JsonProperty("resolution_date")
  private String resolutionDate = null;

  @JsonProperty("resolution_task_ids")
  private List<String> resolutionTaskIds = null;

  @JsonProperty("data")
  private EventData data = null;

  public EventResource id(String id) {
    this.id = id;
    return this;
  }

   /**
   * [Universally unique identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier)
   * @return id
  **/
  @ApiModelProperty(value = "[Universally unique identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier)")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public EventResource creationDate(String creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(value = "")
  public String getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(String creationDate) {
    this.creationDate = creationDate;
  }

  public EventResource resolution(EventResolution resolution) {
    this.resolution = resolution;
    return this;
  }

   /**
   * Get resolution
   * @return resolution
  **/
  @ApiModelProperty(value = "")
  public EventResolution getResolution() {
    return resolution;
  }

  public void setResolution(EventResolution resolution) {
    this.resolution = resolution;
  }

  public EventResource resolutionReason(String resolutionReason) {
    this.resolutionReason = resolutionReason;
    return this;
  }

   /**
   * Users provided reason for resolution
   * @return resolutionReason
  **/
  @ApiModelProperty(value = "Users provided reason for resolution")
  public String getResolutionReason() {
    return resolutionReason;
  }

  public void setResolutionReason(String resolutionReason) {
    this.resolutionReason = resolutionReason;
  }

  public EventResource resolutionDate(String resolutionDate) {
    this.resolutionDate = resolutionDate;
    return this;
  }

   /**
   * Get resolutionDate
   * @return resolutionDate
  **/
  @ApiModelProperty(value = "")
  public String getResolutionDate() {
    return resolutionDate;
  }

  public void setResolutionDate(String resolutionDate) {
    this.resolutionDate = resolutionDate;
  }

  public EventResource resolutionTaskIds(List<String> resolutionTaskIds) {
    this.resolutionTaskIds = resolutionTaskIds;
    return this;
  }

  public EventResource addResolutionTaskIdsItem(String resolutionTaskIdsItem) {
    if (this.resolutionTaskIds == null) {
      this.resolutionTaskIds = new ArrayList<String>();
    }
    this.resolutionTaskIds.add(resolutionTaskIdsItem);
    return this;
  }

   /**
   * Related Task Ids
   * @return resolutionTaskIds
  **/
  @ApiModelProperty(value = "Related Task Ids")
  public List<String> getResolutionTaskIds() {
    return resolutionTaskIds;
  }

  public void setResolutionTaskIds(List<String> resolutionTaskIds) {
    this.resolutionTaskIds = resolutionTaskIds;
  }

  public EventResource data(EventData data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public EventData getData() {
    return data;
  }

  public void setData(EventData data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventResource eventResource = (EventResource) o;
    return Objects.equals(this.id, eventResource.id) &&
        Objects.equals(this.creationDate, eventResource.creationDate) &&
        Objects.equals(this.resolution, eventResource.resolution) &&
        Objects.equals(this.resolutionReason, eventResource.resolutionReason) &&
        Objects.equals(this.resolutionDate, eventResource.resolutionDate) &&
        Objects.equals(this.resolutionTaskIds, eventResource.resolutionTaskIds) &&
        Objects.equals(this.data, eventResource.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, creationDate, resolution, resolutionReason, resolutionDate, resolutionTaskIds, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventResource {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    resolution: ").append(toIndentedString(resolution)).append("\n");
    sb.append("    resolutionReason: ").append(toIndentedString(resolutionReason)).append("\n");
    sb.append("    resolutionDate: ").append(toIndentedString(resolutionDate)).append("\n");
    sb.append("    resolutionTaskIds: ").append(toIndentedString(resolutionTaskIds)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

