/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Profile event type
 */
public enum EventType {
  
  PEP_FLAG("PEP_FLAG"),
  
  SANCTION_FLAG("SANCTION_FLAG"),
  
  DOCUMENT_EXPIRY("DOCUMENT_EXPIRY"),
  
  TRANSACTION_ALERT("TRANSACTION_ALERT"),
  
  REVIEW_NEEDED("REVIEW_NEEDED"),
  
  ADVERSE_MEDIA_FLAG("ADVERSE_MEDIA_FLAG"),
  
  REFER_FLAG("REFER_FLAG");

  private String value;

  EventType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static EventType fromValue(String text) {
    for (EventType b : EventType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}

