/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * The individual&#39;s name. This is broken down into different parts
 */
@ApiModel(description = "The individual's name. This is broken down into different parts")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class FullName {
  @JsonProperty("title")
  private String title;

  @JsonProperty("given_names")
  private List<String> givenNames = null;

  @JsonProperty("family_name")
  private String familyName;

  @JsonProperty("alt_family_names")
  private List<String> altFamilyNames = null;

  public FullName title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The individual&#39;s title
   * @return title
  **/
  @ApiModelProperty(value = "The individual's title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public FullName givenNames(List<String> givenNames) {
    this.givenNames = givenNames;
    return this;
  }

  public FullName addGivenNamesItem(String givenNamesItem) {
    if (this.givenNames == null) {
      this.givenNames = new ArrayList<String>();
    }
    this.givenNames.add(givenNamesItem);
    return this;
  }

   /**
   * An array of the individual&#39;s given (first &amp; middle) names
   * @return givenNames
  **/
  @ApiModelProperty(value = "An array of the individual's given (first & middle) names")
  public List<String> getGivenNames() {
    return givenNames;
  }

  public void setGivenNames(List<String> givenNames) {
    this.givenNames = givenNames;
  }

  public FullName familyName(String familyName) {
    this.familyName = familyName;
    return this;
  }

   /**
   * The individual&#39;s family name (surname)
   * @return familyName
  **/
  @ApiModelProperty(value = "The individual's family name (surname)")
  public String getFamilyName() {
    return familyName;
  }

  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }

  public FullName altFamilyNames(List<String> altFamilyNames) {
    this.altFamilyNames = altFamilyNames;
    return this;
  }

  public FullName addAltFamilyNamesItem(String altFamilyNamesItem) {
    if (this.altFamilyNames == null) {
      this.altFamilyNames = new ArrayList<String>();
    }
    this.altFamilyNames.add(altFamilyNamesItem);
    return this;
  }

   /**
   * An array of the individual&#39;s other family names (surnames). This typically might include a maiden name
   * @return altFamilyNames
  **/
  @ApiModelProperty(value = "An array of the individual's other family names (surnames). This typically might include a maiden name")
  public List<String> getAltFamilyNames() {
    return altFamilyNames;
  }

  public void setAltFamilyNames(List<String> altFamilyNames) {
    this.altFamilyNames = altFamilyNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullName fullName = (FullName) o;
    return Objects.equals(this.title, fullName.title) &&
        Objects.equals(this.givenNames, fullName.givenNames) &&
        Objects.equals(this.familyName, fullName.familyName) &&
        Objects.equals(this.altFamilyNames, fullName.altFamilyNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, givenNames, familyName, altFamilyNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullName {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    givenNames: ").append(toIndentedString(givenNames)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    altFamilyNames: ").append(toIndentedString(altFamilyNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

