/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.InlineResponse2002Companies;

/**
 * InlineResponse2002
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class InlineResponse2002 {
  @JsonProperty("companies")
  private List<InlineResponse2002Companies> companies = null;

  @JsonProperty("errors")
  private List<Error> errors = null;

  public InlineResponse2002 companies(List<InlineResponse2002Companies> companies) {
    this.companies = companies;
    return this;
  }

  public InlineResponse2002 addCompaniesItem(InlineResponse2002Companies companiesItem) {
    if (this.companies == null) {
      this.companies = new ArrayList<InlineResponse2002Companies>();
    }
    this.companies.add(companiesItem);
    return this;
  }

   /**
   * The companies found in the search
   * @return companies
  **/
  @ApiModelProperty(value = "The companies found in the search")
  public List<InlineResponse2002Companies> getCompanies() {
    return companies;
  }

  public void setCompanies(List<InlineResponse2002Companies> companies) {
    this.companies = companies;
  }

  public InlineResponse2002 errors(List<Error> errors) {
    this.errors = errors;
    return this;
  }

  public InlineResponse2002 addErrorsItem(Error errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<Error>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * An array of errors that occurred when the check was performed. Hopefully empty!
   * @return errors
  **/
  @ApiModelProperty(value = "An array of errors that occurred when the check was performed. Hopefully empty!")
  public List<Error> getErrors() {
    return errors;
  }

  public void setErrors(List<Error> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.companies, inlineResponse2002.companies) &&
        Objects.equals(this.errors, inlineResponse2002.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companies, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    
    sb.append("    companies: ").append(toIndentedString(companies)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

