/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineObject
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class InlineObject {
  @JsonProperty("profile_ids")
  private List<String> profileIds = new ArrayList<String>();

  public InlineObject profileIds(List<String> profileIds) {
    this.profileIds = profileIds;
    return this;
  }

  public InlineObject addProfileIdsItem(String profileIdsItem) {
    this.profileIds.add(profileIdsItem);
    return this;
  }

   /**
   * The profile ids which this key should have access to
   * @return profileIds
  **/
  @ApiModelProperty(required = true, value = "The profile ids which this key should have access to")
  public List<String> getProfileIds() {
    return profileIds;
  }

  public void setProfileIds(List<String> profileIds) {
    this.profileIds = profileIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject inlineObject = (InlineObject) o;
    return Objects.equals(this.profileIds, inlineObject.profileIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject {\n");
    
    sb.append("    profileIds: ").append(toIndentedString(profileIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

