/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.CountryCode;

/**
 * Stores the given IP address and the automatically detected country and continent
 */
@ApiModel(description = "Stores the given IP address and the automatically detected country and continent")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class IPLocation {
  @JsonProperty("ip_address")
  private String ipAddress;

  @JsonProperty("country")
  private CountryCode country = null;

  /**
   * The continent where the IP address is located. Automatically detected on a best effort basis
   */
  public enum ContinentEnum {
    AF("AF"),
    
    AN("AN"),
    
    AS("AS"),
    
    EU("EU"),
    
    NA("NA"),
    
    OC("OC"),
    
    SA("SA");

    private String value;

    ContinentEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ContinentEnum fromValue(String text) {
      for (ContinentEnum b : ContinentEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }
  }

  @JsonProperty("continent")
  private ContinentEnum continent;

  public IPLocation ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * The IP address of the individual
   * @return ipAddress
  **/
  @ApiModelProperty(required = true, value = "The IP address of the individual")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public IPLocation country(CountryCode country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public CountryCode getCountry() {
    return country;
  }

  public void setCountry(CountryCode country) {
    this.country = country;
  }

  public IPLocation continent(ContinentEnum continent) {
    this.continent = continent;
    return this;
  }

   /**
   * The continent where the IP address is located. Automatically detected on a best effort basis
   * @return continent
  **/
  @ApiModelProperty(value = "The continent where the IP address is located. Automatically detected on a best effort basis")
  public ContinentEnum getContinent() {
    return continent;
  }

  public void setContinent(ContinentEnum continent) {
    this.continent = continent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IPLocation ipLocation = (IPLocation) o;
    return Objects.equals(this.ipAddress, ipLocation.ipAddress) &&
        Objects.equals(this.country, ipLocation.country) &&
        Objects.equals(this.continent, ipLocation.continent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ipAddress, country, continent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IPLocation {\n");
    
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    continent: ").append(toIndentedString(continent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

