/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PEPs and Sanctions Media Article
 */
@ApiModel(description = "PEPs and Sanctions Media Article")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class MediaArticle {
  @JsonProperty("url")
  private String url;

  @JsonProperty("pdf_url")
  private String pdfUrl;

  @JsonProperty("title")
  private String title;

  @JsonProperty("snippet")
  private String snippet;

  @JsonProperty("date")
  private String date;

  public MediaArticle url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL to article
   * @return url
  **/
  @ApiModelProperty(value = "URL to article")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public MediaArticle pdfUrl(String pdfUrl) {
    this.pdfUrl = pdfUrl;
    return this;
  }

   /**
   * URL to PDF
   * @return pdfUrl
  **/
  @ApiModelProperty(value = "URL to PDF")
  public String getPdfUrl() {
    return pdfUrl;
  }

  public void setPdfUrl(String pdfUrl) {
    this.pdfUrl = pdfUrl;
  }

  public MediaArticle title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of article
   * @return title
  **/
  @ApiModelProperty(value = "Title of article")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public MediaArticle snippet(String snippet) {
    this.snippet = snippet;
    return this;
  }

   /**
   * Article snippet displayed in portal
   * @return snippet
  **/
  @ApiModelProperty(value = "Article snippet displayed in portal")
  public String getSnippet() {
    return snippet;
  }

  public void setSnippet(String snippet) {
    this.snippet = snippet;
  }

  public MediaArticle date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Exact date in &#x60;YYYY-MM-DD&#x60; format
   * @return date
  **/
  @ApiModelProperty(example = "1992-11-24", value = "Exact date in `YYYY-MM-DD` format")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MediaArticle mediaArticle = (MediaArticle) o;
    return Objects.equals(this.url, mediaArticle.url) &&
        Objects.equals(this.pdfUrl, mediaArticle.pdfUrl) &&
        Objects.equals(this.title, mediaArticle.title) &&
        Objects.equals(this.snippet, mediaArticle.snippet) &&
        Objects.equals(this.date, mediaArticle.date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, pdfUrl, title, snippet, date);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MediaArticle {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    pdfUrl: ").append(toIndentedString(pdfUrl)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    snippet: ").append(toIndentedString(snippet)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

