/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.PEPRole;

/**
 * Details of a PEP
 */
@ApiModel(description = "Details of a PEP")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class PEP {
  @JsonProperty("name")
  private String name;

  @JsonProperty("from_date")
  private String fromDate;

  @JsonProperty("to_date")
  private String toDate;

  @JsonProperty("is_current")
  private Boolean isCurrent;

  @JsonProperty("match")
  private Boolean match;

  @JsonProperty("tier")
  private Integer tier;

  @JsonProperty("roles")
  private List<PEPRole> roles = null;

  public PEP name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of PEP
   * @return name
  **/
  @ApiModelProperty(value = "Name of PEP")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PEP fromDate(String fromDate) {
    this.fromDate = fromDate;
    return this;
  }

   /**
   * Partial date, recording a year and possibly month and day. The date will be in one of three formats &#x60;YYYY&#x60;, &#x60;YYYY-MM&#x60;, &#x60;YYYY-MM-DD&#x60;
   * @return fromDate
  **/
  @ApiModelProperty(example = "1992", value = "Partial date, recording a year and possibly month and day. The date will be in one of three formats `YYYY`, `YYYY-MM`, `YYYY-MM-DD`")
  public String getFromDate() {
    return fromDate;
  }

  public void setFromDate(String fromDate) {
    this.fromDate = fromDate;
  }

  public PEP toDate(String toDate) {
    this.toDate = toDate;
    return this;
  }

   /**
   * Partial date, recording a year and possibly month and day. The date will be in one of three formats &#x60;YYYY&#x60;, &#x60;YYYY-MM&#x60;, &#x60;YYYY-MM-DD&#x60;
   * @return toDate
  **/
  @ApiModelProperty(example = "1992", value = "Partial date, recording a year and possibly month and day. The date will be in one of three formats `YYYY`, `YYYY-MM`, `YYYY-MM-DD`")
  public String getToDate() {
    return toDate;
  }

  public void setToDate(String toDate) {
    this.toDate = toDate;
  }

  public PEP isCurrent(Boolean isCurrent) {
    this.isCurrent = isCurrent;
    return this;
  }

   /**
   * Is the PEP in force
   * @return isCurrent
  **/
  @ApiModelProperty(value = "Is the PEP in force")
  public Boolean getIsCurrent() {
    return isCurrent;
  }

  public void setIsCurrent(Boolean isCurrent) {
    this.isCurrent = isCurrent;
  }

  public PEP match(Boolean match) {
    this.match = match;
    return this;
  }

   /**
   * If a PEP was matched
   * @return match
  **/
  @ApiModelProperty(value = "If a PEP was matched")
  public Boolean getMatch() {
    return match;
  }

  public void setMatch(Boolean match) {
    this.match = match;
  }

  public PEP tier(Integer tier) {
    this.tier = tier;
    return this;
  }

   /**
   * The highest tier of the matched PEPs
   * @return tier
  **/
  @ApiModelProperty(value = "The highest tier of the matched PEPs")
  public Integer getTier() {
    return tier;
  }

  public void setTier(Integer tier) {
    this.tier = tier;
  }

  public PEP roles(List<PEPRole> roles) {
    this.roles = roles;
    return this;
  }

  public PEP addRolesItem(PEPRole rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<PEPRole>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * The roles causing the PEP result
   * @return roles
  **/
  @ApiModelProperty(value = "The roles causing the PEP result")
  public List<PEPRole> getRoles() {
    return roles;
  }

  public void setRoles(List<PEPRole> roles) {
    this.roles = roles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PEP PEP = (PEP) o;
    return Objects.equals(this.name, PEP.name) &&
        Objects.equals(this.fromDate, PEP.fromDate) &&
        Objects.equals(this.toDate, PEP.toDate) &&
        Objects.equals(this.isCurrent, PEP.isCurrent) &&
        Objects.equals(this.match, PEP.match) &&
        Objects.equals(this.tier, PEP.tier) &&
        Objects.equals(this.roles, PEP.roles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, fromDate, toDate, isCurrent, match, tier, roles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PEP {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
    sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
    sb.append("    isCurrent: ").append(toIndentedString(isCurrent)).append("\n");
    sb.append("    match: ").append(toIndentedString(match)).append("\n");
    sb.append("    tier: ").append(toIndentedString(tier)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

