/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The current status of the application. * &#x60;APPLIED&#x60;: Can go to &#x60;APPROVED&#x60; or &#x60;REJECTED&#x60;. * &#x60;APPROVED&#x60;: Can go to &#x60;IN_REVIEW&#x60; or &#x60;CANCELLED&#x60;. * &#x60;IN_REVIEW&#x60;: Can go to &#x60;APPROVED&#x60; or &#x60;CANCELLED&#x60;. * &#x60;REJECTED&#x60;: Final state. If a user \&quot;unrejects\&quot; in the UI, it will hide this product application and create a new one with the same history (minus the last rejection). * &#x60;CANCELLED&#x60;: Final state.
 */
public enum ProductApplicationStatus {
  
  APPLIED("APPLIED"),
  
  APPROVED("APPROVED"),
  
  IN_REVIEW("IN_REVIEW"),
  
  REJECTED("REJECTED"),
  
  CANCELLED("CANCELLED");

  private String value;

  ProductApplicationStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ProductApplicationStatus fromValue(String text) {
    for (ProductApplicationStatus b : ProductApplicationStatus.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}

