/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.EntityData;
import org.openapitools.client.model.ProductApplication;
import org.openapitools.client.model.ProfileCategory;
import org.openapitools.client.model.ProfileStatus;
import org.openapitools.client.model.RiskOverviewResource;
import org.openapitools.client.model.Role;
import org.openapitools.client.model.TaskProgress;

/**
 * A customer profile
 */
@ApiModel(description = "A customer profile")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class ProfileResource {
  @JsonProperty("id")
  private String id;

  @JsonProperty("creation_date")
  private String creationDate = null;

  @JsonProperty("role")
  private Role role = null;

  @JsonProperty("collected_data")
  private EntityData collectedData = null;

  @JsonProperty("verified_data")
  private EntityData verifiedData = null;

  @JsonProperty("checks")
  private List checks = null;

  @JsonProperty("collection_steps")
  private List collectionSteps = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("applications")
  private List<ProductApplication> applications = null;

  @JsonProperty("task_types")
  private List taskTypes = null;

  @JsonProperty("tasks")
  private List tasks = null;

  @JsonProperty("events")
  private List events = null;

  @JsonProperty("category")
  private ProfileCategory category = null;

  @JsonProperty("status")
  private ProfileStatus status = null;

  @JsonProperty("document_images")
  private List documentImages = null;

  @JsonProperty("tags")
  private List tags = null;

  @JsonProperty("risk")
  private RiskOverviewResource risk = null;

  @JsonProperty("unresolved_event_types")
  private List unresolvedEventTypes = null;

  @JsonProperty("task_progress")
  private TaskProgress taskProgress = null;

  @JsonProperty("has_associates")
  private Boolean hasAssociates = null;

  @JsonProperty("has_collection_steps")
  private Boolean hasCollectionSteps = null;

  @JsonProperty("linked_to")
  private List linkedTo = null;

  public ProfileResource id(String id) {
    this.id = id;
    return this;
  }

   /**
   * [Universally unique identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier)
   * @return id
  **/
  @ApiModelProperty(value = "[Universally unique identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier)")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ProfileResource creationDate(String creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(value = "")
  public String getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(String creationDate) {
    this.creationDate = creationDate;
  }

  public ProfileResource role(Role role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(value = "")
  public Role getRole() {
    return role;
  }

  public void setRole(Role role) {
    this.role = role;
  }

  public ProfileResource collectedData(EntityData collectedData) {
    this.collectedData = collectedData;
    return this;
  }

   /**
   * Get collectedData
   * @return collectedData
  **/
  @ApiModelProperty(value = "")
  public EntityData getCollectedData() {
    return collectedData;
  }

  public void setCollectedData(EntityData collectedData) {
    this.collectedData = collectedData;
  }

  public ProfileResource verifiedData(EntityData verifiedData) {
    this.verifiedData = verifiedData;
    return this;
  }

   /**
   * Get verifiedData
   * @return verifiedData
  **/
  @ApiModelProperty(value = "")
  public EntityData getVerifiedData() {
    return verifiedData;
  }

  public void setVerifiedData(EntityData verifiedData) {
    this.verifiedData = verifiedData;
  }

  public ProfileResource checks(List checks) {
    this.checks = checks;
    return this;
  }

   /**
   * Get checks
   * @return checks
  **/
  @ApiModelProperty(value = "")
  public List getChecks() {
    return checks;
  }

  public void setChecks(List checks) {
    this.checks = checks;
  }

  public ProfileResource collectionSteps(List collectionSteps) {
    this.collectionSteps = collectionSteps;
    return this;
  }

   /**
   * Get collectionSteps
   * @return collectionSteps
  **/
  @ApiModelProperty(value = "")
  public List getCollectionSteps() {
    return collectionSteps;
  }

  public void setCollectionSteps(List collectionSteps) {
    this.collectionSteps = collectionSteps;
  }

  public ProfileResource displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ProfileResource applications(List<ProductApplication> applications) {
    this.applications = applications;
    return this;
  }

  public ProfileResource addApplicationsItem(ProductApplication applicationsItem) {
    if (this.applications == null) {
      this.applications = new ArrayList<ProductApplication>();
    }
    this.applications.add(applicationsItem);
    return this;
  }

   /**
   * Product applications on profile
   * @return applications
  **/
  @ApiModelProperty(value = "Product applications on profile")
  public List<ProductApplication> getApplications() {
    return applications;
  }

  public void setApplications(List<ProductApplication> applications) {
    this.applications = applications;
  }

  public ProfileResource taskTypes(List taskTypes) {
    this.taskTypes = taskTypes;
    return this;
  }

   /**
   * Get taskTypes
   * @return taskTypes
  **/
  @ApiModelProperty(value = "")
  public List getTaskTypes() {
    return taskTypes;
  }

  public void setTaskTypes(List taskTypes) {
    this.taskTypes = taskTypes;
  }

  public ProfileResource tasks(List tasks) {
    this.tasks = tasks;
    return this;
  }

   /**
   * Get tasks
   * @return tasks
  **/
  @ApiModelProperty(value = "")
  public List getTasks() {
    return tasks;
  }

  public void setTasks(List tasks) {
    this.tasks = tasks;
  }

  public ProfileResource events(List events) {
    this.events = events;
    return this;
  }

   /**
   * Get events
   * @return events
  **/
  @ApiModelProperty(value = "")
  public List getEvents() {
    return events;
  }

  public void setEvents(List events) {
    this.events = events;
  }

  public ProfileResource category(ProfileCategory category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(value = "")
  public ProfileCategory getCategory() {
    return category;
  }

  public void setCategory(ProfileCategory category) {
    this.category = category;
  }

  public ProfileResource status(ProfileStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public ProfileStatus getStatus() {
    return status;
  }

  public void setStatus(ProfileStatus status) {
    this.status = status;
  }

  public ProfileResource documentImages(List documentImages) {
    this.documentImages = documentImages;
    return this;
  }

   /**
   * Get documentImages
   * @return documentImages
  **/
  @ApiModelProperty(value = "")
  public List getDocumentImages() {
    return documentImages;
  }

  public void setDocumentImages(List documentImages) {
    this.documentImages = documentImages;
  }

  public ProfileResource tags(List tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List getTags() {
    return tags;
  }

  public void setTags(List tags) {
    this.tags = tags;
  }

  public ProfileResource risk(RiskOverviewResource risk) {
    this.risk = risk;
    return this;
  }

   /**
   * Get risk
   * @return risk
  **/
  @ApiModelProperty(value = "")
  public RiskOverviewResource getRisk() {
    return risk;
  }

  public void setRisk(RiskOverviewResource risk) {
    this.risk = risk;
  }

  public ProfileResource unresolvedEventTypes(List unresolvedEventTypes) {
    this.unresolvedEventTypes = unresolvedEventTypes;
    return this;
  }

   /**
   * Get unresolvedEventTypes
   * @return unresolvedEventTypes
  **/
  @ApiModelProperty(value = "")
  public List getUnresolvedEventTypes() {
    return unresolvedEventTypes;
  }

  public void setUnresolvedEventTypes(List unresolvedEventTypes) {
    this.unresolvedEventTypes = unresolvedEventTypes;
  }

  public ProfileResource taskProgress(TaskProgress taskProgress) {
    this.taskProgress = taskProgress;
    return this;
  }

   /**
   * Get taskProgress
   * @return taskProgress
  **/
  @ApiModelProperty(value = "")
  public TaskProgress getTaskProgress() {
    return taskProgress;
  }

  public void setTaskProgress(TaskProgress taskProgress) {
    this.taskProgress = taskProgress;
  }

  public ProfileResource hasAssociates(Boolean hasAssociates) {
    this.hasAssociates = hasAssociates;
    return this;
  }

   /**
   * Get hasAssociates
   * @return hasAssociates
  **/
  @ApiModelProperty(value = "")
  public Boolean getHasAssociates() {
    return hasAssociates;
  }

  public void setHasAssociates(Boolean hasAssociates) {
    this.hasAssociates = hasAssociates;
  }

  public ProfileResource hasCollectionSteps(Boolean hasCollectionSteps) {
    this.hasCollectionSteps = hasCollectionSteps;
    return this;
  }

   /**
   * Get hasCollectionSteps
   * @return hasCollectionSteps
  **/
  @ApiModelProperty(value = "")
  public Boolean getHasCollectionSteps() {
    return hasCollectionSteps;
  }

  public void setHasCollectionSteps(Boolean hasCollectionSteps) {
    this.hasCollectionSteps = hasCollectionSteps;
  }

  public ProfileResource linkedTo(List linkedTo) {
    this.linkedTo = linkedTo;
    return this;
  }

   /**
   * Get linkedTo
   * @return linkedTo
  **/
  @ApiModelProperty(value = "")
  public List getLinkedTo() {
    return linkedTo;
  }

  public void setLinkedTo(List linkedTo) {
    this.linkedTo = linkedTo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileResource profileResource = (ProfileResource) o;
    return Objects.equals(this.id, profileResource.id) &&
        Objects.equals(this.creationDate, profileResource.creationDate) &&
        Objects.equals(this.role, profileResource.role) &&
        Objects.equals(this.collectedData, profileResource.collectedData) &&
        Objects.equals(this.verifiedData, profileResource.verifiedData) &&
        Objects.equals(this.checks, profileResource.checks) &&
        Objects.equals(this.collectionSteps, profileResource.collectionSteps) &&
        Objects.equals(this.displayName, profileResource.displayName) &&
        Objects.equals(this.applications, profileResource.applications) &&
        Objects.equals(this.taskTypes, profileResource.taskTypes) &&
        Objects.equals(this.tasks, profileResource.tasks) &&
        Objects.equals(this.events, profileResource.events) &&
        Objects.equals(this.category, profileResource.category) &&
        Objects.equals(this.status, profileResource.status) &&
        Objects.equals(this.documentImages, profileResource.documentImages) &&
        Objects.equals(this.tags, profileResource.tags) &&
        Objects.equals(this.risk, profileResource.risk) &&
        Objects.equals(this.unresolvedEventTypes, profileResource.unresolvedEventTypes) &&
        Objects.equals(this.taskProgress, profileResource.taskProgress) &&
        Objects.equals(this.hasAssociates, profileResource.hasAssociates) &&
        Objects.equals(this.hasCollectionSteps, profileResource.hasCollectionSteps) &&
        Objects.equals(this.linkedTo, profileResource.linkedTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, creationDate, role, collectedData, verifiedData, checks, collectionSteps, displayName, applications, taskTypes, tasks, events, category, status, documentImages, tags, risk, unresolvedEventTypes, taskProgress, hasAssociates, hasCollectionSteps, linkedTo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileResource {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    collectedData: ").append(toIndentedString(collectedData)).append("\n");
    sb.append("    verifiedData: ").append(toIndentedString(verifiedData)).append("\n");
    sb.append("    checks: ").append(toIndentedString(checks)).append("\n");
    sb.append("    collectionSteps: ").append(toIndentedString(collectionSteps)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    applications: ").append(toIndentedString(applications)).append("\n");
    sb.append("    taskTypes: ").append(toIndentedString(taskTypes)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    documentImages: ").append(toIndentedString(documentImages)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    risk: ").append(toIndentedString(risk)).append("\n");
    sb.append("    unresolvedEventTypes: ").append(toIndentedString(unresolvedEventTypes)).append("\n");
    sb.append("    taskProgress: ").append(toIndentedString(taskProgress)).append("\n");
    sb.append("    hasAssociates: ").append(toIndentedString(hasAssociates)).append("\n");
    sb.append("    hasCollectionSteps: ").append(toIndentedString(hasCollectionSteps)).append("\n");
    sb.append("    linkedTo: ").append(toIndentedString(linkedTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

