/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.SanctionTimePeriods;

/**
 * Details of a sanction
 */
@ApiModel(description = "Details of a sanction")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class Sanction {
  @JsonProperty("issuer")
  private String issuer;

  @JsonProperty("name")
  private String name;

  @JsonProperty("kind")
  private String kind;

  @JsonProperty("list")
  private String list;

  @JsonProperty("is_current")
  private Boolean isCurrent;

  @JsonProperty("is_past")
  private Boolean isPast;

  @JsonProperty("type")
  private String type;

  @JsonProperty("time_periods")
  private List<SanctionTimePeriods> timePeriods = null;

  public Sanction issuer(String issuer) {
    this.issuer = issuer;
    return this;
  }

   /**
   * Name of issuing authority
   * @return issuer
  **/
  @ApiModelProperty(value = "Name of issuing authority")
  public String getIssuer() {
    return issuer;
  }

  public void setIssuer(String issuer) {
    this.issuer = issuer;
  }

  public Sanction name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of Sanction
   * @return name
  **/
  @ApiModelProperty(value = "Name of Sanction")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Sanction kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind of Sanction
   * @return kind
  **/
  @ApiModelProperty(value = "Kind of Sanction")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public Sanction list(String list) {
    this.list = list;
    return this;
  }

   /**
   * Sanction list containing this sanction
   * @return list
  **/
  @ApiModelProperty(value = "Sanction list containing this sanction")
  public String getList() {
    return list;
  }

  public void setList(String list) {
    this.list = list;
  }

  public Sanction isCurrent(Boolean isCurrent) {
    this.isCurrent = isCurrent;
    return this;
  }

   /**
   * Is the Sanction in force
   * @return isCurrent
  **/
  @ApiModelProperty(value = "Is the Sanction in force")
  public Boolean getIsCurrent() {
    return isCurrent;
  }

  public void setIsCurrent(Boolean isCurrent) {
    this.isCurrent = isCurrent;
  }

  public Sanction isPast(Boolean isPast) {
    this.isPast = isPast;
    return this;
  }

   /**
   * Is the Sanction no longer in force
   * @return isPast
  **/
  @ApiModelProperty(value = "Is the Sanction no longer in force")
  public Boolean getIsPast() {
    return isPast;
  }

  public void setIsPast(Boolean isPast) {
    this.isPast = isPast;
  }

  public Sanction type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Sanction type
   * @return type
  **/
  @ApiModelProperty(value = "Sanction type")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Sanction timePeriods(List<SanctionTimePeriods> timePeriods) {
    this.timePeriods = timePeriods;
    return this;
  }

  public Sanction addTimePeriodsItem(SanctionTimePeriods timePeriodsItem) {
    if (this.timePeriods == null) {
      this.timePeriods = new ArrayList<SanctionTimePeriods>();
    }
    this.timePeriods.add(timePeriodsItem);
    return this;
  }

   /**
   * Date range of Sanction
   * @return timePeriods
  **/
  @ApiModelProperty(value = "Date range of Sanction")
  public List<SanctionTimePeriods> getTimePeriods() {
    return timePeriods;
  }

  public void setTimePeriods(List<SanctionTimePeriods> timePeriods) {
    this.timePeriods = timePeriods;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sanction sanction = (Sanction) o;
    return Objects.equals(this.issuer, sanction.issuer) &&
        Objects.equals(this.name, sanction.name) &&
        Objects.equals(this.kind, sanction.kind) &&
        Objects.equals(this.list, sanction.list) &&
        Objects.equals(this.isCurrent, sanction.isCurrent) &&
        Objects.equals(this.isPast, sanction.isPast) &&
        Objects.equals(this.type, sanction.type) &&
        Objects.equals(this.timePeriods, sanction.timePeriods);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuer, name, kind, list, isCurrent, isPast, type, timePeriods);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sanction {\n");
    
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("    isCurrent: ").append(toIndentedString(isCurrent)).append("\n");
    sb.append("    isPast: ").append(toIndentedString(isPast)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    timePeriods: ").append(toIndentedString(timePeriods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

