/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.DefaultSanctionsResult;
import org.openapitools.client.model.Identification;
import org.openapitools.client.model.Location;

/**
 * Result of a PEPs and Sanctions Check
 */
@ApiModel(description = "Result of a PEPs and Sanctions Check")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class SanctionsResult extends DefaultSanctionsResult {
  @JsonProperty("is_enhanced")
  private Boolean isEnhanced;

  @JsonProperty("gender")
  private String gender;

  @JsonProperty("pep_rating")
  private String pepRating;

  @JsonProperty("remarks")
  private List<String> remarks = null;

  @JsonProperty("deceased")
  private Boolean deceased;

  @JsonProperty("disqualified_director")
  private Boolean disqualifiedDirector;

  @JsonProperty("insolvent")
  private Boolean insolvent;

  @JsonProperty("law_enforcement")
  private Boolean lawEnforcement;

  @JsonProperty("riskography")
  private String riskography;

  @JsonProperty("deceased_dates")
  private List<String> deceasedDates = null;

  @JsonProperty("inactive_as_rca_related_to_pep_dates")
  private List<String> inactiveAsRcaRelatedToPepDates = null;

  @JsonProperty("inactive_as_pep_dates")
  private List<String> inactiveAsPepDates = null;

  @JsonProperty("identifications")
  private List<Identification> identifications = null;

  @JsonProperty("locations")
  private List<Location> locations = null;

  public SanctionsResult isEnhanced(Boolean isEnhanced) {
    this.isEnhanced = isEnhanced;
    return this;
  }

   /**
   * If this is an enchanced Sanctions result
   * @return isEnhanced
  **/
  @ApiModelProperty(value = "If this is an enchanced Sanctions result")
  public Boolean getIsEnhanced() {
    return isEnhanced;
  }

  public void setIsEnhanced(Boolean isEnhanced) {
    this.isEnhanced = isEnhanced;
  }

  public SanctionsResult gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Gender of match
   * @return gender
  **/
  @ApiModelProperty(value = "Gender of match")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public SanctionsResult pepRating(String pepRating) {
    this.pepRating = pepRating;
    return this;
  }

   /**
   * PEP Rating
   * @return pepRating
  **/
  @ApiModelProperty(value = "PEP Rating")
  public String getPepRating() {
    return pepRating;
  }

  public void setPepRating(String pepRating) {
    this.pepRating = pepRating;
  }

  public SanctionsResult remarks(List<String> remarks) {
    this.remarks = remarks;
    return this;
  }

  public SanctionsResult addRemarksItem(String remarksItem) {
    if (this.remarks == null) {
      this.remarks = new ArrayList<String>();
    }
    this.remarks.add(remarksItem);
    return this;
  }

   /**
   * Sanction remarks from data provider
   * @return remarks
  **/
  @ApiModelProperty(value = "Sanction remarks from data provider")
  public List<String> getRemarks() {
    return remarks;
  }

  public void setRemarks(List<String> remarks) {
    this.remarks = remarks;
  }

  public SanctionsResult deceased(Boolean deceased) {
    this.deceased = deceased;
    return this;
  }

   /**
   * If the result is deceased
   * @return deceased
  **/
  @ApiModelProperty(value = "If the result is deceased")
  public Boolean getDeceased() {
    return deceased;
  }

  public void setDeceased(Boolean deceased) {
    this.deceased = deceased;
  }

  public SanctionsResult disqualifiedDirector(Boolean disqualifiedDirector) {
    this.disqualifiedDirector = disqualifiedDirector;
    return this;
  }

   /**
   * If the result is a disqualified director
   * @return disqualifiedDirector
  **/
  @ApiModelProperty(value = "If the result is a disqualified director")
  public Boolean getDisqualifiedDirector() {
    return disqualifiedDirector;
  }

  public void setDisqualifiedDirector(Boolean disqualifiedDirector) {
    this.disqualifiedDirector = disqualifiedDirector;
  }

  public SanctionsResult insolvent(Boolean insolvent) {
    this.insolvent = insolvent;
    return this;
  }

   /**
   * If the result is a insolvent
   * @return insolvent
  **/
  @ApiModelProperty(value = "If the result is a insolvent")
  public Boolean getInsolvent() {
    return insolvent;
  }

  public void setInsolvent(Boolean insolvent) {
    this.insolvent = insolvent;
  }

  public SanctionsResult lawEnforcement(Boolean lawEnforcement) {
    this.lawEnforcement = lawEnforcement;
    return this;
  }

   /**
   * If the result is a member of law enforcement
   * @return lawEnforcement
  **/
  @ApiModelProperty(value = "If the result is a member of law enforcement")
  public Boolean getLawEnforcement() {
    return lawEnforcement;
  }

  public void setLawEnforcement(Boolean lawEnforcement) {
    this.lawEnforcement = lawEnforcement;
  }

  public SanctionsResult riskography(String riskography) {
    this.riskography = riskography;
    return this;
  }

   /**
   * Description of PEP or sanctioned persons background
   * @return riskography
  **/
  @ApiModelProperty(value = "Description of PEP or sanctioned persons background")
  public String getRiskography() {
    return riskography;
  }

  public void setRiskography(String riskography) {
    this.riskography = riskography;
  }

  public SanctionsResult deceasedDates(List<String> deceasedDates) {
    this.deceasedDates = deceasedDates;
    return this;
  }

  public SanctionsResult addDeceasedDatesItem(String deceasedDatesItem) {
    if (this.deceasedDates == null) {
      this.deceasedDates = new ArrayList<String>();
    }
    this.deceasedDates.add(deceasedDatesItem);
    return this;
  }

   /**
   * Reported death dates
   * @return deceasedDates
  **/
  @ApiModelProperty(value = "Reported death dates")
  public List<String> getDeceasedDates() {
    return deceasedDates;
  }

  public void setDeceasedDates(List<String> deceasedDates) {
    this.deceasedDates = deceasedDates;
  }

  public SanctionsResult inactiveAsRcaRelatedToPepDates(List<String> inactiveAsRcaRelatedToPepDates) {
    this.inactiveAsRcaRelatedToPepDates = inactiveAsRcaRelatedToPepDates;
    return this;
  }

  public SanctionsResult addInactiveAsRcaRelatedToPepDatesItem(String inactiveAsRcaRelatedToPepDatesItem) {
    if (this.inactiveAsRcaRelatedToPepDates == null) {
      this.inactiveAsRcaRelatedToPepDates = new ArrayList<String>();
    }
    this.inactiveAsRcaRelatedToPepDates.add(inactiveAsRcaRelatedToPepDatesItem);
    return this;
  }

   /**
   * Dates of relation to PEP cessation
   * @return inactiveAsRcaRelatedToPepDates
  **/
  @ApiModelProperty(value = "Dates of relation to PEP cessation")
  public List<String> getInactiveAsRcaRelatedToPepDates() {
    return inactiveAsRcaRelatedToPepDates;
  }

  public void setInactiveAsRcaRelatedToPepDates(List<String> inactiveAsRcaRelatedToPepDates) {
    this.inactiveAsRcaRelatedToPepDates = inactiveAsRcaRelatedToPepDates;
  }

  public SanctionsResult inactiveAsPepDates(List<String> inactiveAsPepDates) {
    this.inactiveAsPepDates = inactiveAsPepDates;
    return this;
  }

  public SanctionsResult addInactiveAsPepDatesItem(String inactiveAsPepDatesItem) {
    if (this.inactiveAsPepDates == null) {
      this.inactiveAsPepDates = new ArrayList<String>();
    }
    this.inactiveAsPepDates.add(inactiveAsPepDatesItem);
    return this;
  }

   /**
   * Dates of PEP inactivity
   * @return inactiveAsPepDates
  **/
  @ApiModelProperty(value = "Dates of PEP inactivity")
  public List<String> getInactiveAsPepDates() {
    return inactiveAsPepDates;
  }

  public void setInactiveAsPepDates(List<String> inactiveAsPepDates) {
    this.inactiveAsPepDates = inactiveAsPepDates;
  }

  public SanctionsResult identifications(List<Identification> identifications) {
    this.identifications = identifications;
    return this;
  }

  public SanctionsResult addIdentificationsItem(Identification identificationsItem) {
    if (this.identifications == null) {
      this.identifications = new ArrayList<Identification>();
    }
    this.identifications.add(identificationsItem);
    return this;
  }

   /**
   * Identifications such as a passport
   * @return identifications
  **/
  @ApiModelProperty(value = "Identifications such as a passport")
  public List<Identification> getIdentifications() {
    return identifications;
  }

  public void setIdentifications(List<Identification> identifications) {
    this.identifications = identifications;
  }

  public SanctionsResult locations(List<Location> locations) {
    this.locations = locations;
    return this;
  }

  public SanctionsResult addLocationsItem(Location locationsItem) {
    if (this.locations == null) {
      this.locations = new ArrayList<Location>();
    }
    this.locations.add(locationsItem);
    return this;
  }

   /**
   * Locations related to a PEP or sanctioned entity, such as birth place
   * @return locations
  **/
  @ApiModelProperty(value = "Locations related to a PEP or sanctioned entity, such as birth place")
  public List<Location> getLocations() {
    return locations;
  }

  public void setLocations(List<Location> locations) {
    this.locations = locations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SanctionsResult sanctionsResult = (SanctionsResult) o;
    return Objects.equals(this.isEnhanced, sanctionsResult.isEnhanced) &&
        Objects.equals(this.gender, sanctionsResult.gender) &&
        Objects.equals(this.pepRating, sanctionsResult.pepRating) &&
        Objects.equals(this.remarks, sanctionsResult.remarks) &&
        Objects.equals(this.deceased, sanctionsResult.deceased) &&
        Objects.equals(this.disqualifiedDirector, sanctionsResult.disqualifiedDirector) &&
        Objects.equals(this.insolvent, sanctionsResult.insolvent) &&
        Objects.equals(this.lawEnforcement, sanctionsResult.lawEnforcement) &&
        Objects.equals(this.riskography, sanctionsResult.riskography) &&
        Objects.equals(this.deceasedDates, sanctionsResult.deceasedDates) &&
        Objects.equals(this.inactiveAsRcaRelatedToPepDates, sanctionsResult.inactiveAsRcaRelatedToPepDates) &&
        Objects.equals(this.inactiveAsPepDates, sanctionsResult.inactiveAsPepDates) &&
        Objects.equals(this.identifications, sanctionsResult.identifications) &&
        Objects.equals(this.locations, sanctionsResult.locations) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isEnhanced, gender, pepRating, remarks, deceased, disqualifiedDirector, insolvent, lawEnforcement, riskography, deceasedDates, inactiveAsRcaRelatedToPepDates, inactiveAsPepDates, identifications, locations, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SanctionsResult {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    isEnhanced: ").append(toIndentedString(isEnhanced)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    pepRating: ").append(toIndentedString(pepRating)).append("\n");
    sb.append("    remarks: ").append(toIndentedString(remarks)).append("\n");
    sb.append("    deceased: ").append(toIndentedString(deceased)).append("\n");
    sb.append("    disqualifiedDirector: ").append(toIndentedString(disqualifiedDirector)).append("\n");
    sb.append("    insolvent: ").append(toIndentedString(insolvent)).append("\n");
    sb.append("    lawEnforcement: ").append(toIndentedString(lawEnforcement)).append("\n");
    sb.append("    riskography: ").append(toIndentedString(riskography)).append("\n");
    sb.append("    deceasedDates: ").append(toIndentedString(deceasedDates)).append("\n");
    sb.append("    inactiveAsRcaRelatedToPepDates: ").append(toIndentedString(inactiveAsRcaRelatedToPepDates)).append("\n");
    sb.append("    inactiveAsPepDates: ").append(toIndentedString(inactiveAsPepDates)).append("\n");
    sb.append("    identifications: ").append(toIndentedString(identifications)).append("\n");
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

