/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PassFort&#39;s supported task types
 */
public enum TaskType {
  
  INDIVIDUAL_VERIFY_IDENTITY("INDIVIDUAL_VERIFY_IDENTITY"),
  
  INDIVIDUAL_VERIFY_ADDRESS("INDIVIDUAL_VERIFY_ADDRESS"),
  
  INDIVIDUAL_VERIFY_SOURCE_OF_FUNDS("INDIVIDUAL_VERIFY_SOURCE_OF_FUNDS"),
  
  INDIVIDUAL_ASSESS_MEDIA_AND_POLITICAL_AND_SANCTIONS_EXPOSURE("INDIVIDUAL_ASSESS_MEDIA_AND_POLITICAL_AND_SANCTIONS_EXPOSURE"),
  
  INDIVIDUAL_ASSESS_POLITICAL_AND_SANCTIONS_EXPOSURE("INDIVIDUAL_ASSESS_POLITICAL_AND_SANCTIONS_EXPOSURE"),
  
  INDIVIDUAL_ASSESS_POLITICAL_EXPOSURE("INDIVIDUAL_ASSESS_POLITICAL_EXPOSURE"),
  
  INDIVIDUAL_ASSESS_SANCTIONS_EXPOSURE("INDIVIDUAL_ASSESS_SANCTIONS_EXPOSURE"),
  
  INDIVIDUAL_VERIFY_BANK_ACCOUNT("INDIVIDUAL_VERIFY_BANK_ACCOUNT"),
  
  INDIVIDUAL_MANUAL_TASK("INDIVIDUAL_MANUAL_TASK"),
  
  COMPANY_VERIFY_IDENTITY("COMPANY_VERIFY_IDENTITY"),
  
  COMPANY_VERIFY_CHARITY("COMPANY_VERIFY_CHARITY"),
  
  COMPANY_IDENTIFY_AUTHORIZED_PERSONS("COMPANY_IDENTIFY_AUTHORIZED_PERSONS"),
  
  COMPANY_IDENTIFY_OFFICERS("COMPANY_IDENTIFY_OFFICERS"),
  
  COMPANY_IDENTIFY_TRUSTEES("COMPANY_IDENTIFY_TRUSTEES"),
  
  COMPANY_IDENTIFY_BENEFICIAL_OWNERS("COMPANY_IDENTIFY_BENEFICIAL_OWNERS"),
  
  COMPANY_REVIEW_FILINGS("COMPANY_REVIEW_FILINGS"),
  
  COMPANY_ASSESS_SANCTIONS_EXPOSURE("COMPANY_ASSESS_SANCTIONS_EXPOSURE"),
  
  COMPANY_ASSESS_MEDIA_EXPOSURE("COMPANY_ASSESS_MEDIA_EXPOSURE"),
  
  COMPANY_ASSESS_MEDIA_AND_SANCTIONS_EXPOSURE("COMPANY_ASSESS_MEDIA_AND_SANCTIONS_EXPOSURE"),
  
  COMPANY_MANUAL_TASK("COMPANY_MANUAL_TASK"),
  
  COMPANY_VERIFY_BANK_ACCOUNT("COMPANY_VERIFY_BANK_ACCOUNT"),
  
  COMPANY_VERIFY_TAX_STATUS("COMPANY_VERIFY_TAX_STATUS");

  private String value;

  TaskType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TaskType fromValue(String text) {
    for (TaskType b : TaskType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}

