/*
 * PassFort API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@passfort.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.TaxIdType;

/**
 * Companies tax identifiers
 */
@ApiModel(description = "Companies tax identifiers")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-02-06T16:01:27.451+11:00[Australia/Sydney]")
public class TaxId {
  @JsonProperty("tax_id_type")
  private TaxIdType taxIdType = null;

  @JsonProperty("value")
  private String value;

  public TaxId taxIdType(TaxIdType taxIdType) {
    this.taxIdType = taxIdType;
    return this;
  }

   /**
   * Get taxIdType
   * @return taxIdType
  **/
  @ApiModelProperty(required = true, value = "")
  public TaxIdType getTaxIdType() {
    return taxIdType;
  }

  public void setTaxIdType(TaxIdType taxIdType) {
    this.taxIdType = taxIdType;
  }

  public TaxId value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Tax identifier value
   * @return value
  **/
  @ApiModelProperty(required = true, value = "Tax identifier value")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxId taxId = (TaxId) o;
    return Objects.equals(this.taxIdType, taxId.taxIdType) &&
        Objects.equals(this.value, taxId.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taxIdType, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxId {\n");
    
    sb.append("    taxIdType: ").append(toIndentedString(taxIdType)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

